### ISSUE TITLE
 MIP1 改造 MIP2 迁移注意事项 [DRAFT]

### ISSUE THREAD

**Issue by PengXing** [mipengine/mip2#1]
MIP2 和 MIP1 大体上一样，但还是有一些点不太一样，需要在迁移内置组件的时候注意，并且遵循以下规范

> 以下规范还是 Draft，随时会更新

## 代码规范

- 使用 es6 和 ES Module 编写组件
- 全部代码需要通过 eslint 审核才能提交，遵循[社区 standard 规范](https://standardjs.com/rules-zhcn.html)
- 不到万不得已，不许使用 `eslint-disable`
- Vue 的 template 部分需要遵守 Vue 的编码规范

[JS 代码规范](https://standardjs.com/rules-zhcn.html)
[Vue 规范](https://cn.vuejs.org/v2/style-guide/index.html)

## MIP1 需要改造的点
- MIP 组件采用 customElement v1 标准 或者通过编写 Vue 来实现，参考文档 [组件生命周期](https://github.com/mipengine/mip2/blob/master/docs/components/instance-life-cycle.md)
- MIP1 页面存在大量操作全局的操作，如 `mip-nav-slidedown`，作为一个浏览器的自定义标签，居然把事件代理到 `document`，customElement 只能负责自己的逻辑，尽量不要越界
- MIP2 组件编写方式和 MIP 1 有很大变化，有两种方式，1. 通过 extends MIP.BaseElement，然后重写父类的方法来编写 MIP2 的组件 2. 编写 Vue 文件
- MIP2 中将 `isIframed` 这个变量的含义改变了，判断是否在搜索结果页通过 `MIP.standalone` 来判断，代替具有歧义的 `viewer.isIframed` 变量
- 不要写 `let me = this` 这样的语句，如遇到这种情况，请使用箭头函数

**Comment by VenyXiong** [comment]
"全部代码需要通过 fecs 审核才能提交"
今天看到群里说是是需要循序社区规范而不是fecs, 这条规则是不是要更新下?

**Comment by PengXing** [comment]
我来更新一下

**Comment by easonyq** [comment]
# `viewer.isIframed` 的使用

在老版本 MIP 中，`view.isIframed` 同时拥有两种含义：
1. 在不在 iframe 里面（也是字面意思）。例如mip里面对ios fixed的处理就在这个变量为 `true` 的分支里面。
2. 在不在搜索页里面，例如要 `postMessage` 给 SF 的时候。

在新版本 MIP 中，因为 DOM 结构的关系，这个变量 __仅用作第一种含义__，即 __仅能用来判断是否在 iframe 里面__。用作第二种含义时，应当使用 `window.MIP.standalone` 变量来判断，为 `true` 表示 __不在搜索结果页中__。
