### ISSUE TITLE
vue组件bug

### ISSUE THREAD

**Issue by xin-** [mipengine/mip2#104]
**BUG 描述**
会导致，例如v-if="show", show设置为false，组件未消失，并且未进入update钩子

**复现步骤**
详细信息已经和辉泉沟通过，已定位到是6.27上线之后导致的，但是问题可能比较难找

**期望结果**
正常

**截图**

**环境及版本信息:**
 - mip-cli Version

**其他信息**

**Comment by huanghuiquan** [comment]
**问题定位**

问题已经定位，是由于 mip-fixed 组件导致的，mip-fixed 组件在 iOS 下为解决滚动抖动的问题，会把子mip-fixed 组件移动到和 body 同级，导致 vue 组件无法更新 ui。

**解决方案**
只有需要滚动的固定元素的需求才需要解决抖动问题，mip-fixed 将通过属性标明是否要移动到body同级解决滚动抖动的问题 @xiaoiver
