### ISSUE TITLE
shell在设置iframe的页面高度时候会偶现计算错误，影响页面内的底部内容展示

### ISSUE THREAD

**Issue by Espoir-L** [mipengine/mip2#106]
**BUG 描述**
在翻页以后页面高度的变化后，有时没有触发resize，导致iframe的高度没有重新计算，影响页面内底部内容的展示，在safair下偶现频率较高；

**复现步骤**
重新复现 Bug 的步骤
线上搜索query『雪中悍刀行』，翻页以后，有时候偶现页面底部内容展示不全的问题

**期望结果**
由于现在小说每页底部加了凤巢二期的广告，如果页面显示不全，会影响广告的展示，期望可以展示全部内容，改为轮训的方式获取高度；

**截图**
![image](https://user-images.githubusercontent.com/25815613/43441839-bd0090aa-94ce-11e8-8646-76b6277ba1f2.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by easonyq** [comment]
已经加上了每 500ms 进行一次轮询。现在会重新检查并设置所有 iframe 大小的情况有：
1. `resize` 事件捕获时
2. 切换页面时
3. 每 500ms

**Comment by easonyq** [comment]
根据实际使用情况，现在已修改成了每 250ms 触发一次
