### ISSUE TITLE
在sf环境下点击下一页不能进行滑动，android uc 

### ISSUE THREAD

**Issue by zhuguoxi** [mipengine/mip2#107]
**BUG 描述**
在sf环境下点击下一页不能进行滑动，android uc 

**复现步骤**
1. 目前有两个项目可复现
https://m.baidu.com/wishwing/c/s/baoxian.baidu.com/mip/index
https://m.baidu.com/wishwing/c/s/b.kuaifawu.com/index/index.html
点击 shell button后 可恢复滚动

**环境及版本信息:**
 - android uc

**Comment by easonyq** [comment]
虽然查不到原因，但我尝试了一个修复方案，已经发布到BOS，你验证下OK的话，我就合并到master去了。
