### ISSUE TITLE
大图模式下不要显示<mip-shell>组件

### ISSUE THREAD

**Issue by ClimbYU** [mipengine/mip2#108]
点击显示大图模式时会显示顶部的mip-shell，但点击左上角的返回按钮时不会回到进入大图之前的页面，而是会退出整个页面。建议在大图模式下要mip-shell组件不显示这样就不会退出当前页面

**Comment by easonyq** [comment]
shell头部那个就是页面后退，并不是返回，所以点了肯定是会切换页面了。

核心原因应该是子页面所在的 iframe 并不占满屏幕，因此即便 mip-img 的大图预览情况下，也依然没法挡住头。所以只要和对话框一样，想办法把头遮住就行了。

我来修改一下mip-img的实现吧。

**Comment by easonyq** [comment]
已经修复&提交，近期会上线。
