### ISSUE TITLE
不支持同时暴露多个组件

### ISSUE THREAD

**Issue by jenkey2011** [mipengine/mip2#11]
## 背景 与 需求

迁移 mip 选项卡组件<br/>
**目前的最佳实现**：`<mip-vd-tabs/>`为选项卡容器，`<vd-tab/>` 为选项卡，根据站长的需求，数量不一定。期望的结构如下

```html
<!-- 这是 HTML 文件，非 Vue 单文件 -->

<mip-vd-tabs>
  <vd-tab name="标签1" :selected="true">
    <h2> MIP 2.0 </h2>
    <p> 内容11111 </p>
  </vd-tab>
  <vd-tab name="标签2">
    <p> 内容222222 </p>  
  </vd-tab>
  <vd-tab name="标签3">
    <p> 内容333333 </p>  
  </vd-tab>
  ...
</mip-vd-tabs>
```

效果如图：

![2018-06-14 13_36_47](https://user-images.githubusercontent.com/20010737/41395217-74bd9c52-6fdf-11e8-810b-ea13dbc6b7dd.gif)

## 问题

组件`<mip-vd-tabs/>`导入`<vd-tab/>`，可正常注册并使用。但在 HTML 中（即站长使用时），子组件（`<vd-tab/>`）无法被解析。因为只导出了`<mip-vd-tabs/>`组件，`<vd-tab/>`是没有暴露出来的。

## 不支持暴露多个组件的其他方案

拿选项卡为例

- DOM 操作： 用`<slot/>`插入 dom，然后在`<mip-vd-tabs/>`组件内， 选中元素、属性、遍历、赋值……

```html
<!-- 用 slot  -->

<mip-vd-tabs>
  <div name="标签1" class="active">
    <h2>MIP 2.0</h2>
    <p> 内容11111 </p>
  </div>
  <div name="标签2">
    <p> 内容222222 </p>  
  </div>
  <div name="标签3">
    <p> 内容333333 </p>  
  </div>
  ...
</mip-vd-tabs>
```

- 传`json`数据
  - json 传输的内容限制太大
  - 站长改造升级不平滑
  - 选项卡内容不易自定义结构

```html
<!-- 用 json  -->

<mip-vd-tabs>
  <script type="application/json">
    {
      "items": [{
          "name": "标签1",
          "content": "<h2>MIP 2.0</h2><p>内容11111</p>"
        },{
          "name": "标签2",
          "content": "<p>内容22222</p>"
        },{
          "name": "标签3",
          "content": "<p>内容33333</p>"
        },{
          ...
        }
      ]
    }
  </script>
</mip-vd-tabs>
```

## 需求场景

在 html 中任意插入子组件，升级成本低、结构直观、 子组件嵌套的内容自定义方便

- 选项卡

  ```html
  <mip-vd-tabs>
    <vd-tab>  </vd-tab>
    <vd-tab>  </vd-tab>
    <vd-tab>  </vd-tab>

    ...

  </mip-vd-tabs>
  ```

- 焦点图

  ```html
  <mip-carousel>
    <carousel-item>  </carousel-item>
    <carousel-item>  </carousel-item>
    <carousel-item>  </carousel-item>

    ...

  </mip-carousel>
  ```

- ...

**Comment by clark-t** [comment]
在目前现有的组件构建方案里面，可以考虑把 mip-vd-tabs 和 vd-tab 分别弄成两个组件 在 html 里引入即可达到你想要的效果

**Comment by jenkey2011** [comment]
@clark-t  单独开发两个组件确实可以，有俩问题
- 两个是配套的组件，但是需要分别引入两个js文件，提测、管理、上线，都比较麻烦，关联性太低
- 如果一个组件需要拆分成三个五个，那这无疑增加了组件的数量，想想mip1，700+的站长组件……

**Comment by PengXing** [comment]
这个问题的解决方案呢？节前其实已经有结论了， @clark-t 这个可以写一下
