### ISSUE TITLE
mip-link 上有 on="xxx" 时不会触发 href 跳转

### ISSUE THREAD

**Issue by clark-t** [mipengine/mip2#111]
**BUG 描述**
当 mip-link 也就是带有 `data-type="mip"` 标记的 a 链，假设在这个 a 链上存在 `on="xxx"` 的事件绑定语法，就会导致 a 链 href 跳转失效。

`on="xxx"` 分以下情况：
1. 当 on 事件绑定只是做了 mip-data 相关操作比如 `on="tap:MIP.setData({a:1})"` 不会导致 a 链跳转失效；
2. 当 on 事件绑定调用另一个 mip 组件的事件，如 `on="tap:lightbox.close"` 则 a 链跳转失效；

目前未尝试在 on 事件绑定中同时进行 MIP.setData 和 lightbox.close 的操作。

出现这种情况的实际应用场景为：

点击打开侧边栏之后点击文章链接，在跳转的同时需要收起侧边栏以体现行为的连贯性，但目前加了 on 事件绑定之后侧边栏是能收起来了，但是页面跳转并没发生。

**复现步骤**
假设页面为 /b.html 点击跳转时会触发 lightbox 的弹窗行为，但是不会触发原有的 href 跳转
```html
<body>
  <a class="btn" data-type="mip" href="/a.html" on="tap:my-lightbox.toggle">to a</a>
  <mip-lightbox
    id="my-lightbox"
    layout="nodisplay"
    class="mip-hidden">
    <div class="lightbox">
      <h1>Hello, World!</h1>
    </div>
  </mip-lightbox>
  <script src="https://c.mipcdn.com/static/v2/mip.js"></script>
  <script src="https://c.mipcdn.com/static/v1/mip-lightbox/mip-lightbox.js"></script>
</body>
```
目前只弹出了 lightbox 但是页面并没有跳转至 /a.html

**期望结果**
弹出 lightbox 的同时切换页面到 /a.html

**Comment by easonyq** [comment]
我稍微调试了一下，觉得要请 @huanghuiquan  协助

### 调试结论
1. 是不是 on 的处理代码执行了例如 `preventDefault` 之类的操作？
2. 为啥 dev 模式和线上模式表现不同，很费解。

### 调试内容

在 dev 模式下，一切正常，因为 viewer 里面捕获 a 链接的代码正常运行，如下：

![image](https://user-images.githubusercontent.com/6800839/43560732-84c43e34-9646-11e8-9a16-02bf307be56c.png)

但是在访问线上的 mip.js 地址时，断点却没法断到，从而导致了只响应 on 而不响应跳转，如下：

![image](https://user-images.githubusercontent.com/6800839/43560704-5ff07b86-9646-11e8-8323-b3a7023c6a89.png)

**Comment by easonyq** [comment]
> 线下没问题应该是代码没更新，之前淼江改了一个了一下 executeEventAction，加了 setTimeout，使得 lightbox 的 preventDefault 被延迟了，所以看起来没问题：

昨天下午刚上过线，意思是他在上线到今天这几个小时内改的是吗？

**Comment by huanghuiquan** [comment]
@easonyq 上线是担心有问题，临时改回来的
