### ISSUE TITLE
mip-carousel不能频繁切换

### ISSUE THREAD

**Issue by gy0318** [mipengine/mip2#112]
**BUG 描述**
通过自定义的tab(不少于两个)切换控制轮播图的显示，来会切换会导致mip-carousel多出一些空的div，导致轮播图会有空白页的显示，并且图片偶尔会拍成一列，上下抖动闪烁显示，稳定以后显示空白页。

**复现步骤**
重新复现 Bug 的步骤
1、有两个自定义的tab，来回切换时，会动态渲染mip-carousel；
2、从第一个tab切换至第二个tab，此时的mip-carousel会貌似缓存前一次的子元素，但是此时并没有数据去渲染缓存过来的元素，导致轮播图出现一些空白的页面；
**期望结果**
希望轮播图可以稳定显示

**截图**
![image](https://user-images.githubusercontent.com/31302941/43561432-a30d6b56-9649-11e8-8a75-8fd73c134bf7.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by ccksfh** [comment]
@gy0318 你好，我对你的描述有些疑问：
1. “通过tab切换控制轮播图”，这里的 tab 是指什么？是圆点的 indicator，还是左右切换箭头的 buttonController，还是你自定义的 tab？
2. 复现步骤不好理解，请加以文字描述操作步骤
谢谢

**Comment by ccksfh** [comment]
@gy0318 你好，我看到你的 update 了，但是我对你说的会动态渲染 mip-carousel 的过程仍然有些疑问，请具体描述一下你的动态渲染过程：
你是在切换 tab 的过程动态插入不同的新的 mip-carousel 呢？还是有固定的两个 carousel，通过某些条件，更改 hide/show 动态显隐呢？还是只有一个 carousel，通过动态地调整数据，以调整 mip-carousel 下的子元素呢？etc.

我会先尝试一下，可以的话最好请你以代码的形式提供你的 case，谢谢

**Comment by ccksfh** [comment]
@gy0318 

我用这样简单的场景试了一下，复现了你描述中的 “切换会导致mip-carousel多出一些空的div” 的问题

```html
  template: `<div class="mip-dynamic-carousel">
      <div class="tabs">
        <p @click="to(1)">1</p>
        <p @click="to(2)">2</p>
      </div>
      <mip-carousel v-if="list && list.length"
        class="carousel-1"
        layout="responsive"
        width="600" 
        height="400">
        <mip-img v-for="img in list"
          :src="img" :key="img">
        </mip-img>
      </mip-carousel>
      <mip-carousel v-if="list2 && list2.length"
        class="carousel-2"
        layout="responsive"
        width="600" 
        height="400">
        <mip-img v-for="img in list2"
          :src="img" :key="img">
        </mip-img>
      </mip-carousel>
    </div>
  `,
  data: () => {
    return {
      list: [],
      list2: []
    }
  },
  methods: {
    to (tabNum) {
      if (tabNum === 1) {
        this.list2 = []
        this.list = [
          'https://www.mipengine.org/static/img/sample_01.jpg',
          'https://www.mipengine.org/static/img/sample_02.jpg'
        ]
      } else {
        this.list = []
        this.list2 = [
          'https://www.mipengine.org/static/img/sample_03.jpg',
          'https://www.mipengine.org/static/img/sample_04.jpg'
        ]
      }
    }
  },
  prerenderAllowed () {
    return true
  }
```

以我的代码为例，空 div 是数据引起的，在切换 tab 之后，能从标签属性上判断 mip-carousel 已经切换到第二个，但是内容却不是新的。这是因为 Vue的 virtual dom 机制 在做 diff 的时候，会认为这次切换，节点无需 remove 后再 insert，只需要在原节点的基础上 patch 更新，更新属性/子节点。如果没有经过节点的更换，MIP 自定义组件核心也依然会视两者为同一个 mip-carousel 组件，不重新执行自定义组件的编译运行等工作。
这个问题，可以通过在 vue 组件的模板中，在不同的 mip-carousel 标签上添加 key 属性来解决。如下：

```html
<mip-carousel v-if="list && list.length"
  key="carousel-1"
  class="carousel-1"
  ...>
  <mip-img v-for="img in list"
    :src="img" :key="img">
  </mip-img>
</mip-carousel>
<mip-carousel v-if="list2 && list2.length"
  key="carousel-2"
  class="carousel-2"
  ...>
  <mip-img v-for="img in list2"
    :src="img" :key="img">
  </mip-img>
</mip-carousel>
```

如果你的需求也符合类似的场景，可以考虑先尝试使用 key 属性来解决问题。

**Comment by gy0318** [comment]
我们的是固定的两个 mip-carousel，通过点击自定义的tab,动态控制mip-carousel的显示和隐藏，通过给不同的 mip-carousel 上添加 key 属性，这个问题已经解决了，谢谢解答！
