### ISSUE TITLE
在大图模式下可以左右滑动查看下一张图，并且能够增加自定义内容

### ISSUE THREAD

**Issue by ClimbYU** [mipengine/mip2#113]
从轮播图进入查看大图，大图不能左右滑动，只能查看当前点击的大图，这个能不能优化一下让大图也可以跟轮播图一样左右进行查看。而且在大图模式下可以增加一些自定义内容，类似于下面这种 
![k0c xx n7rdw 5l e 4 n](https://user-images.githubusercontent.com/26087303/43561439-a79b5908-9649-11e8-948b-f507fbfde314.png)

**Comment by PengXing** [comment]
大图模式下是可以左右滑动的，现在已经提供支持了，可以参考这个 ISSUE https://github.com/mipengine/mip2/issues/50

大图模式下支持自定义内容估计不会支持，`mip-carousel` 组件可以考虑这个事情，我们调研一下

**Comment by craigchencc** [comment]
`mip-carousel`组件目前支持增加数字指示器，增加副标题，增加翻页按钮等自定义行为，具体使用可查看[官网链接](https://www.mipengine.org/v2/components/builtin/mip-carousel.html)
