### ISSUE TITLE
MIP Shell页面切换时支持引入缓存过的历史页面的状态

### ISSUE THREAD

**Issue by ShawnTu** [mipengine/mip2#114]
**要解决什么问题**
MIP Shell在页面切换时可以考虑引入历史页面的状态。
场景描述：在MIP Shell底部导航栏点击tab打开了A，浏览到了某一位置，再点击另一个tab打开了B，再点击另一个tab打开了C，如果这时再次点击tab打开A，还想要定位到刚才的位置

**描述一下你理想中的解决方案**
在MIP.viewer.open()中添加参数，表示优先走缓存

**Comment by easonyq** [comment]
已经合并到 master 并上线，等待 @ShawnTu  验证无误后关闭 issue

**Comment by easonyq** [comment]
如果目标页面不存在，依然会以正常流程加载页面，因此叫做 `fromCache` 不太确切。

最终我改名叫作 `cacheFirst`，如果在 `<a>`， 则形如 `<a href="xxx" mip-cache cache-first>`
