### ISSUE TITLE
无法监听页面的滚动

### ISSUE THREAD

**Issue by gy0318** [mipengine/mip2#118]
**BUG 描述**
在自定义组件中
window.addEventListener('scroll',this.handleScroll);
使用这个方式，放在iframe中的页面，在Android系统中，可以监听到页面的滚动，但是在ios系统中，无法监听页面的滚动；
 this.$el.addEventListener('scroll',this.handleScroll);
或者将监听事件绑定到某个dom元素上，也是无法监听到滚动事件的；

**复现步骤**
重新复现 Bug 的步骤

**期望结果**

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by xiaoiver** [comment]
请使用 `viewport` 相关的 API：
