### ISSUE TITLE
mip-img组件的 `popup` 属性，点击图片弹层存在显示不全的情况

### ISSUE THREAD

**Issue by liuruoran88** [mipengine/mip2#119]
**BUG 描述**
mip-img 组件的popup 属性设置后，点击图片弹层，图片宽度等于视口的宽度，同比例调整高度后如果图片的高度仍然大于视口高度时，图片仍然居中显示，导致图片显示不全的问题，且弹层中不支持滚动浏览整个图片。

**复现步骤**
```html
<mip-img popup src="http://bos.nj.bpc.baidu.com/v1/assets/mip/mip2-component-lifecycle.png"></mip-img>
```

**期望结果**
当图片弹层全屏显示后，高度超出视口，则视口显示图片头部，并可通过滚动浏览全图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by liuruoran88** [comment]
问题已修复，之前弹层没考虑到这种弹层图片超高的情况，这里做了相应的处理

[问题定位代码](https://github.com/mipengine/mip2/blob/f5b81901a9a640fe0226bc5f0ed8dfec1f0e1976/packages/mip/src/components/mip-img.js#L45)

**Comment by yuyutong** [comment]
测试报告
