### ISSUE TITLE
mip-cli dev 不支持js 后加md5戳，会导致浏览器缓存

### ISSUE THREAD

**Issue by s-s-k** [mipengine/mip2#12]
mip-cli dev 不支持js 文件加md5戳，会导致浏览器缓存，手机预览时需要清理缓存

![image](https://user-images.githubusercontent.com/15928370/41726059-e666a7b2-75a3-11e8-8e09-a855e7e28c1a.png)

自己查看源码后发现是：html 是通过自己的中间件生成，js通过webpack 中间件生成，这两者之间没有通信机制
现在的机制是： html 为静态文件，js 是每次请求都要编译一次
解决方案： 能否通过webpack 插件来处理html 并对其中的相对路径进行替换并添加md5 戳，将产出html 
 js文件输出到静态目录（可以是硬盘或内存）如果文件有更新，编译完毕后通过websocket 进行推送访问此地址的页面应该刷新了

**Comment by PengXing** [comment]
@clark-t 我记得 mip-cli 开发组件的是有 HMR 的？

**Comment by s-s-k** [comment]
是有HRM 的 但是js文件是没有md5 时间戳后缀的

**Comment by clark-t** [comment]
建议不错，目前可以通过浏览器勾选 Disable cache 解决，后续 cli 会加上该功能 @s-s-k

**Comment by clark-t** [comment]
@s-s-k mip-cli@1.0.13 版本已实现该功能

**Comment by PengXing** [comment]
你没说咋使用啊 。。

**Comment by shao-kang** [comment]
@clark-t  直接升级 mip-cli 版本就行了吗？
