### ISSUE TITLE
本地json中 连字符属性，无法正常读取

### ISSUE THREAD

**Issue by jenkey2011** [mipengine/mip2#121]
**BUG 描述**
之前是驼峰无法读取 ： #59 
现在是连字符无法读取…… 

**复现步骤**
本地json中 连字符属性

```js
{
  "hide-map": true,  // this.hideMap 读取不到自定义的值
  "getPosition": true  // 正常
}
```

**期望结果**
两种都可以读取，因为这两种属性写法 都在用…… 

**截图**

**环境及版本信息:**
 - OS: mac
 - Browser chrome
 - 浏览器 67
 - mip-cli 1.20

**其他信息**
无

**Comment by PengXing** [comment]
这个的支持去掉了

**Comment by jenkey2011** [comment]
关了
