### ISSUE TITLE
IOS 10 UIWebview 跳其他域名后回退后白屏

### ISSUE THREAD

**Issue by tayqassqan** [mipengine/mip2#122]
**BUG 描述**
如标题

**环境及版本信息:**
 - OS: IOS 10
 - Browser UIWebview内核浏览器

复现URL：https://m.baidu.com/wishwing/c/s/jin.baidu.com/v/mipicash

**Comment by easonyq** [comment]
在该页面情况下，因为是跨域链接且目标页非MIP，因此直接采用 `window.top.location.href=xxxx` 这样的普通跳转。而后退会有问题，应该是ios本身的缓存引发的，如 [这里](https://stackoverflow.com/questions/8788802/prevent-safari-loading-from-cache-when-back-button-is-clicked) 所述。

关于这个 `persisted` 和 `pageshow` ，其实 MIP1 的代码里也有相关的处理（但是只判断ios 8 & 9，不包括10）。__不过我觉得重点应该是在 SF 的代码里，因为是 SF 把我们容纳进了 iframe，后退也是先运行他的代码。__

可以尝试下直接访问 jin.baidu.com/v/mipicash 看看是否有这问题？

**Comment by easonyq** [comment]
在 MIP1 的代码中，已经有相关的操作，只是没有针对 ios10，我周末已经加上&提交了，diff如下：

```diff
let needBackReload = (iosVersion === '8' && platform.isUc() && screen.width === 320) ||
-  (iosVersion === '9' && platform.isSafari())
+  (iosVersion === '9' && platform.isSafari()) ||
+  (iosVersion === '10' && platform.isSafari())
if (needBackReload) {
  window.addEventListener('pageshow', e => {
    if (e.persisted) {
      document.body.style.display = 'none'
      location.reload()
    }
  })
}
```

**Comment by tayqassqan** [comment]
MIP1的页面也出现类似问题，貌似这个问题不能完全解决，之前MIP1结论是UC广告屏蔽引起的，这里需要验证一下。

**Comment by easonyq** [comment]
这个问题以前在 IOS 8 & 9 能复现么？如果不能，那我这次改动应该就能解决了

**Comment by easonyq** [comment]
之前理解错误，以为只是 safari 的问题，是我审题不清。
我手边的 IOS 10 可以在 UC 和 手百 上复现，因此我把两种浏览器都加入了判断。百度浏览器虽然不会复现，但因为我身边没有 IOS 8 9 的机器，所以不太确定，因此也一并加上了。
