### ISSUE TITLE
<mip-fixed> 导致首屏其他元素位置计算有误

### ISSUE THREAD

**Issue by yenshih** [mipengine/mip2#125]
**BUG 描述**
带 hash 的路由刷新时，首屏会依次执行
https://github.com/mipengine/mip2/blob/master/packages/mip/src/index.js#L128
https://github.com/mipengine/mip2/blob/master/packages/mip/src/viewer.js#L71
https://github.com/mipengine/mip2/blob/master/packages/mip/src/page/index.js#L172

此时注册 mip 组件的步骤还未执行
https://github.com/mipengine/mip2/blob/master/packages/mip/src/index.js#L141

导致 `<mip-fixed>` 占用了额外的空间，影响了 `scrollToHash` 中 `offsetTop` 的计算。

**复现步骤**
重新复现 Bug 的步骤
1. 前往 [此处](https://mip-project.github.io/guide/mip-advanced/mip-speed-principle.html#%E6%AD%A3%E7%A1%AE%E5%8A%A0%E8%BD%BD%E5%A4%96%E9%83%A8%E6%96%87%E4%BB%B6)
2. 发现 hash 滚动位置不准确

**期望结果**
hash 滚动位置准确

**截图**
![image](https://user-images.githubusercontent.com/14069488/43695398-0f46d59a-996b-11e8-89ed-eb8e077a7eb7.png)

**环境及版本信息:**
 - OS: macOS 10.12.6
 - Browser Chrome
 - 浏览器 Version 68

**Comment by xiaoiver** [comment]
需要等所有组件 loaded 之后再进行滚动，才能避免滚动位置的错乱。
目前 MIP 里 performance 有统计首屏时间，也就是所有组件 loaded 的时间。大致原理就是每个组件 loaded 之后通知 performance，检查下数量决定是否全体 loaded。
```JAVASCRIPT
// performance.js
function tryRecordFirstScreen () {
  if (recorder.MIPFirstScreen) {
    return
  }
  fsElements.length === 0 && recordTiming('MIPFirstScreen')
}
```

所以可以在这时候进行滚动到锚点：
```JAVASCRIPT
// page.js
performance.on('update', timing => {
  if (timing.MIPFirstScreen) {
    // scroll to current hash if exists
    this.scrollToHash(window.location.hash)
  }
})
```
