### ISSUE TITLE
小说shell中在root上配置了shellConfig后在点击目录页每次刷新shell的时候，processShellConfig并没有重新执行，导致header.bouncy失效

### ISSUE THREAD

**Issue by Espoir-L** [mipengine/mip2#132]
**BUG 描述**
清晰和准确的描述 Bug 是什么

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by easonyq** [comment]
核心原因在于
* 小说的配置 `alwaysReadConfigOnLoad` 为 `true`，因此每次加载页面都需要读取页面配置并更新
* `processShellConfig` 只作用于 root page
* `meta.header.bouncy` 默认值为 `true`

这就导致了虽然在 `processShellConfig` 内部强制设定了 `bouncy = false` ，但只要切换一次页面，新页面的 `bouncy` 又变成了默认值 `true`。

解决方案是在读取后续页面时，增加一个 `processShellConfigInLeaf` 方法，允许子类继承并修改，这样就能实现功能，也能对 `shellConfig` 做全面的修改，避免漏网之鱼
