### ISSUE TITLE
为什么不在沙盒中注入customEvent

### ISSUE THREAD

**Issue by shao-kang** [mipengine/mip2#143]
在使用mip2 cil 1.1.4 版本时可以使用自定义事件 CustomEvent， 
到了1.2.1 版本后就不可以使用了customEvent 自定义事件了。
customEvent 的使用场景是在使用websocket 时触发不同事件， 来解决使用一个巨大的switch语句块问题

**Comment by clark-t** [comment]
mip2@1.2.2 版本发布修复该问题
