### ISSUE TITLE
m-bind 改为绑定属性值本身，而不是字符串

### ISSUE THREAD

**Issue by yenshih** [mipengine/mip2#145]
**要解决什么问题**

在使用 Vue CustomElement 时，有如下情况
```html
<mip-data>
  <script type="application/json">
    {"current": 1}
  </script>
</mip-data>

<mip-v-btn-toggle m-bind:input-value="current">
  <!-- ... -->
</mip-v-btn-toggle>
```
此时对应的 Vue Component 中，`this.inputValue` 的值为 `'1'`，而不是期望的 `1`，导致后续逻辑错误。

**描述一下你理想中的解决方案**

目前类型转换逻辑在 [此处](https://github.com/mipengine/mip2/blob/dev/packages/mip/src/vue-custom-element/index.js#L75)。
考虑将 `convertAttributeValue` 的调用提前。

**Comment by huanghuiquan** [comment]
可以通过 json 的方式传入，避免类型转换：

```html
<mip-v-btn-toggle>
  <script>
  {
   "current": 1
  }
  </script>
  <!-- ... -->
</mip-v-btn-toggle>
```
