### ISSUE TITLE
mip-video组件的autoplay属性在真机上不生效

### ISSUE THREAD

**Issue by gy0318** [mipengine/mip2#158]
**BUG 描述**
mip-video组件的autoplay在电脑的浏览器上调试时，是可以生效的，但是在真机上并没有生效，试过手百，qq浏览器，safari浏览器都没有生效；

**复现步骤**
重新复现 Bug 的步骤
不管是在首页或者是在之后的iframe页面中，都不能生效；
使用的是文档中提供的demo，引用在组件中的example下的html文件中，autoplay并未生效；

**期望结果**
1、希望视频组件的autoplay属性可以生效；
2、希望可以提供属性或者方法可以监听视频组件的视频播放和视频暂停；

**截图**
![image](https://user-images.githubusercontent.com/31302941/43891400-c5fd5b50-9bfb-11e8-928d-58f6c0897782.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by craigchencc** [comment]
1、`autoplay`属性根据不同浏览器的不同版本会有不同的策略，目前Safari从IOS10开始支持自动播放，但仍需满足一定条件，例如添加属性`muted`，所以这个属性主要取决于浏览器的实现。

2、视频组件播放和暂停的方法可以在后续提供。
