### ISSUE TITLE
mip-video  需要对外暴露常见的 video 操作api.

### ISSUE THREAD

**Issue by VenyXiong** [mipengine/mip2#160]
**要解决什么问题**
开发者可以自己对mip-video进行一些个性化操作，暂停、播放、seekTo等。

**描述一下你理想中的解决方案**
mip-video  对外暴露常见的video 操作api.

**描述你的备选方案**

**补充信息**
mediaElement 常见的的属性事件和api可以参考：
https://developer.mozilla.org/zh-CN/docs/Web/Guide/Events/Media_events

**Comment by craigchencc** [comment]
目前我们可以提供video的方法有：play()、pause()、seekTo(currentTime)、canPlayType(mediaType)，可支持的video属性有'ads', 'src', 'controls', 'loop', 'autoplay', 'autobuffer', 'crossorigin', 'height', 'muted', 'preload','poster', 'width', 'currenttime'，麻烦将还需要支持的内容列一下，谢谢！

**Comment by VenyXiong** [comment]
现在已有的属性应该都什么问题，辛苦优先支持下play和pause吧~

**Comment by craigchencc** [comment]
好的

**Comment by yuyutong** [comment]
测试报告
1、暂停按钮兼容性测试
发现bug：ios的qq、uc浏览器下无法暂停播放；ios10、ios11简单搜索下点击暂停按钮失效
测试结论：
ios uc下无法暂停播放问题不解决、ios10/ios11简单搜索下点击暂停按钮失效问题不解决
其他功能正常，测试通过
2、播放按钮兼容性测试
测试结论：测试通过
3、跳到固定时间点按钮的兼容性测试
发现bug：ios10、ios11简单搜索下点击跳转固定时间点按钮失效
测试结论：bug不解决，其他功能测试通过

兼容性覆盖：
iphone7p ios10
iphone6  ios11
iphone5s ios8
SM G9200 7.0
oppo A57 6.0
zuk 5.1.1
SM N9008 4.4.2
uc、qq、chrome、safari/自带浏览器、手百、极速手百、简单搜索
