### ISSUE TITLE
mip-video组件在iframe页面中不能正常播放

### ISSUE THREAD

**Issue by gy0318** [mipengine/mip2#172]
**BUG 描述**
视频在本地测试是可以正常播放的，但是构建以后放到服务器上，进入视频页面，点击播放按钮，视频无法播放，必须刷新页面，才能正常播放

**复现步骤**
重新复现 Bug 的步骤
1、视频组件在本地是可以正常播放的，但是通过构建以后挂到服务器上，首次进入视频页面，视频无法正常播放；
2. 通过首页进入含有视频的页面，视频上有一个播放按钮，但是点击按钮，视频无法播放；
检查元素样式为：图一所示
3、刷新页面之后，点击播放按钮视频才能正常播放，检查元素样式为：图二所示

**期望结果**
希望修复该bug，并暴露一些常用的video事件，供我们开发人员使用

**截图**
首次进入：
![image](https://user-images.githubusercontent.com/31302941/43988370-03c67f4a-9d67-11e8-839e-7cb1c6471040.png)
图一：
![image](https://user-images.githubusercontent.com/31302941/43988375-243798ae-9d67-11e8-986f-5001a03f6013.png)
刷新页面后
![image](https://user-images.githubusercontent.com/31302941/43988379-4a407d86-9d67-11e8-8f5a-1f01a3bf8f00.png)
图二：
![image](https://user-images.githubusercontent.com/31302941/43988387-6edcc6ae-9d67-11e8-989d-8c799b31acd1.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by craigchencc** [comment]
请问iframe页面src是不是https？video的src看起来是http?
