### ISSUE TITLE
vue-awesome-swiper

### ISSUE THREAD

**Issue by hanchanghong** [mipengine/mip2#178]
**要申请的 npm 包名**
多个 npm 包名需要换行

**描述一下添加该 npm 包的必要性**
清晰准确的描述为什么需要这个 npm 包

**补充信息**
补充其他信息，如截图等

**Comment by clark-t** [comment]
mip 核心已经自带了一个 mip-carousel 基本涵盖了 vue-awesome-swiper 的功能实现，你看看项目里面能否替换成 mip-carousel
