### ISSUE TITLE
Vue 组件使用 extends 时，父组件 render 函数未被调用

### ISSUE THREAD

**Issue by yenshih** [mipengine/mip2#184]
**BUG 描述**
Vue 组件使用 extends 时，父组件 render 函数未被调用

**复现步骤**
```shell
cd mip2
git checkout dev-vuetify
npm run dev
```
```shell
cd mip2-ui-components
npm run dev
```
前往 VSlider，发现组件未被渲染
相关代码在这：
https://github.com/mipengine/mip2-ui-components/blob/master/src/components/VSlider/VSlider.js#L16
https://github.com/mipengine/mip2-ui-components/blob/master/src/components/VInput/VInput.js#L223

**期望结果**
render 函数被调用了

**环境及版本信息:**
 - OS: macOS 10.12.6
 - Browser Chrome
 - 浏览器 Version 68

**Comment by huanghuiquan** [comment]
之前没考虑 extends 组件的情况，为了屏蔽 warning 添加了默认 render 函数，这种做法实际上是不可取的：
1. Vue 组件必须有 render 函数，如果没有，应该报warning
2. 直接判断 options 否有 render 函数，没有考虑 mixin 和 extends 两种情况下的 render，这两者情况的render 函数被忽略

[具体代码位置](https://github.com/mipengine/mip2/blob/dev/packages/mip/src/vue-custom-element/index.js#L17-L20)

**解决方案**
直接删除添加默认 render 函数的代码
