### ISSUE TITLE
mip-shell点击下一页的时候，title没有根据新页面的title变化

### ISSUE THREAD

**Issue by Espoir-L** [mipengine/mip2#187]
**BUG 描述**
在加了shell的站点翻页时，title没有重绘。由于延用了MIP1的shell的逻辑，在每次重绘title的时候，拿到配置并不是当前页面的配置，所以导致title并没有修改，

**复现步骤**
重新复现 Bug 的步骤
![image](https://user-images.githubusercontent.com/25815613/44194849-d0b59800-a169-11e8-8535-799ec24c7118.png)
此处的title不会重绘

**期望结果**
为了保持mip1和极速服务不受影响，期望给出一个配置项可有个性化shell去配置。

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by easonyq** [comment]
这个问题的出现和之前一次的修复 #150 有关。

## 问题分析

经过那次修复之后，在切换页面时，为了和 MIP1 保持一致，标题的获取分别有 3 层优先级：
1. `<a>` 的 `data-title`
2. __当前页面__ `<mip-shell>` 中的配置
3. `<a>` 的 `innerText`

因为 loading 需要使用目标页面的标题，所以必须注意 __这 3 层优先级都是在目标页面载入之前就计算完成的。__

之后到目标页面加载完成，更新头部时，也按照上述 3 层优先级获取并更新。

小说的业务逻辑的特殊性在于：__每个页面的 `<mip-shell>` 的配置是不同的__。这就导致了无论是 3 种情况的哪一种，都不是正确的情况，小说其实想要的是目标页面的配置，和极速服务以及 MIP1 的逻辑并不相同

## 解决方案

为 MIPShell 基类增加一个配置项 `this.alwaysUseTitleInShellConfig = false`，由子类 Shell 继承并修改为 `true`。在目标页面加载完成更新头部时，根据这个值决定使用目标页面的配置还是原先的 3 层优先级。

为了避免对已有线上服务产生影响，默认值 `false` 保持原有逻辑，即使用原先的 3 层优先级。

**Comment by Espoir-L** [comment]
需要在个性化shell中的子类的构造函数里面，多写一句
this.alwaysUseTitleInShellConfig = true，才可以在翻页的时候，重新渲染新的title。
