### ISSUE TITLE
iOS 下 UC/手百 切换页面造成未响应

### ISSUE THREAD

**Issue by xiaoiver** [mipengine/mip2#19]
## 问题描述

在进行页面切换时，会把当前的 `<iframe>` 进行隐藏/展现，使用 `display: none`。
但是在 iOS 的 **UC/手百** 下，切换时会出现页面不响应，假死的现象，十分奇怪。

打开这个简单的 **_测试页面 /mip/examples/page/iframe/uc.html_** ，就可以复现，步骤如下：
1. 原始页面使用 `<iframe>` 嵌入一个测试页面 `scroll.html`
2. 点击隐藏按钮隐藏掉整个 iframe
3. 原始页面不响应，表现为无法滚动，按钮无法点击等等

测试页面 `scroll.html` 包含一个菜单，使用了 iOS 弹性滚动。另外还包含以下测试：
1. 嵌入 `m.baidu`，`AMP 页面` 都会出现这种情况。而 PC 百度，eleme H5 则不会出现。
2. 使用以下方法隐藏 `<iframe>` 同样会出问题：
  - `visibility: hidden`
  - `opacity: 0` + `height: 0` + `width: 0`

## 可能的原因

微信不存在这个问题，因为在 iOS 下使用了较新的 WKWebview。
而 UC/手百 使用的是 UIWebView。除了这个奇怪的问题，还有诸如 **scroll 事件延迟** 等其他滚动相关的问题，[详见](https://harttle.land/2018/06/23/uiwebview-bugs.html)。

有问题的页面使用了弹性滚动 `-webkit-overflow-scrolling: touch;`。
而一旦不使用这个属性，或者在隐藏 iframe 的同时由被嵌入的页面去掉这个属性，就不会出现问题。
```javascript
// 需要在隐藏的同时去掉 -webkit-overflow-scrolling: touch;
iframe.contentDocument.querySelector('.menu').classList.remove('touch-scrolling')
```

## 解决方案

第一种比较直接，就是判断处于 **UC/手百** 下，在页面切换时，就直接删除 iframe，而不是隐藏。

第二种就是在页面切换也就是隐藏 iframe 时，关闭掉所有组件的弹性滚动。
但是这样做的问题就是，内置的组件还好办，用户写的组件也会使用到弹性滚动，这就要求页面切换时需要通知所有的组件，让用户做这样的操作。

**Comment by xiaoiver** [comment]
最终使用了这种方法覆盖掉弹性滚动：
在页面 `<iframe>` 隐藏时插入一段固定的 `<style>* {-webkit-overflow-scrolling: auto!important;}</style>`，再次展示时删除。

**Comment by oott123** [comment]
有个问题：如果在结果页使用 superframe 打开，结果页也会有一个隐藏 iframe 的逻辑。理论上，也需要 MIP 页面里面去做这个事情。是不是应该加个 message 来搞？
@tayqassqan @easonyq 看看。要不结果页直接删 iframe 也行，反正 UIWebview 缓存可能也会卡。

**Comment by xiaoiver** [comment]
目前只判断了：
