### ISSUE TITLE
vue-awesome-swiper vue-baidu-map

### ISSUE THREAD

**Issue by hanchanghong** [mipengine/mip2#193]
**要申请的 npm 包名**
多个 npm 包名需要换行

**描述一下添加该 npm 包的必要性**
清晰准确的描述为什么需要这个 npm 包

**补充信息**
补充其他信息，如截图等

**Comment by clark-t** [comment]
请麻烦按照格式提申请 并且说明添加该 npm 包的必要性
上个申请打回的理由是内置的 mip-carousel 可能满足 vue-awesome-swiper 的功能需求，请描述 mip-carousel 在您的项目里不能替代 vue-awesome-swiper 的原因，同时 vue-baidu-map 也有对应的 mip-map
