### ISSUE TITLE
当使用mip-shell时，如果json配置错误是否可在控制台抛出错误信息

### ISSUE THREAD

**Issue by Espoir-L** [mipengine/mip2#204]
**要解决什么问题**
1、在使用mip-shell的时候，如果json配置错误，并不会在控制台抛出错误信息，而是返回shell里写的默认信息，这样导致问题定位比较困难；
2、在开发个性化mip-shell的json配置时，有时候配置错层级，比如下图的view的配置应该和header同级，但是有时候开发者在使用的时候，是放到了meta的同级下，这个在个性化shell的对外可用的方法里会在this.currentPageMeta也可以拿到view的值，但是是个shell内部默认的false的值，最终导致追踪定位问题比较困难，不知道是否可以针对这种类型的问题，抛出异常；
![image](https://user-images.githubusercontent.com/25815613/44451226-aeb68c80-a625-11e8-8738-e2a62fb3df2b.png)

**描述一下你理想中的解决方案**
针对1的问题，是否可以抛出错误信息；
针对2的问题，是否可以抛出异常信息；
**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

**Comment by easonyq** [comment]
问题1可以解决，我会加上错误信息。

问题2就有点见仁见智了，因为 MIP Shell 的所有配置项都是可选的，甚至这个标签本身也可以删除，所以用户配置缺失的部分会由默认配置提供。因此不知道线上有多少情况是不写全的（估计大多数？）如果都抛警告，不知道大家能否忍受。

说大家，其实主要也就是小说和极速服务两方面。现在既然小说有这个需求， @zhuguoxi 极速服务方面觉得如何？来讨论下吧？
