### ISSUE TITLE
npm 白名单校验对异常情况进行容错处理

### ISSUE THREAD

**Issue by chenqiushi** [mipengine/mip2#205]
**BUG 描述**

开发者反馈，站长提交组件(mip2-extensions-platform)时，如果站点没有使用任何第三方依赖，因为某种原因，站点目录中的 package.json 文件被删除了或忘记提交，在执行编译流程时，mip2 build 会去检查 npm 依赖白名单，因为读不到 dependencies 导致代码报错，build 流程中断，影响正常上线。

具体问题应该在 mip-component-validator 模块：

https://github.com/mipengine/mip2/blob/ac232149743420e1f4111fbb37f7fc50e7500aba/packages/mip-component-validator/src/rules/component-npm-whitelist.js#L78-L82

**复现步骤**

1. 移除某个站点的 package.json
2. 提交站长组件代码

**期望结果**

对上述情况进行容错

**截图**

![image](https://user-images.githubusercontent.com/5038140/44503113-37393980-a6c7-11e8-9e98-fe31fa512dbb.png)

**Comment by PengXing** [comment]
开发者提交第三方组件的时候，也会跑 netlify，这个阶段已经知道会编译出错了，为什么会合进来从而影响正常上线呢？

**Comment by clark-t** [comment]
这个是校验工具少了个package.json 缺少 dependencies 导致的，但这个问题在组件本地开发的时候就直接会抛出才是...

**Comment by chenqiushi** [comment]
除了 @clark-t 提到的bug，经过排查，的确也发现了 @PengXing 提及的问题。

当前 netlify 预览编译时调用 mip2 build 的方式和上线编译不一致，导致预览编译没有经过 npm 白名单校验的流程，所以出现了 netlify 能跑过，上线编译才抛出异常的现象。已经改成使用同种方式构建。

**Comment by clark-t** [comment]
最新版 MIP-CLI 已修复
