### ISSUE TITLE
目前还没有mip2的沙盒环境

### ISSUE THREAD

**Issue by jenkey2011** [mipengine/mip2#21]
mip2组件缺少沙盒环境，FE及QA无法使用沙盒进行全流程测试

**Comment by PengXing** [comment]
没懂是啥意思，MIP2 第三方组件不是默认就包在沙盒环境下运行的吗？

**Comment by zoumiaojiang** [comment]
应该指的是关于 mip 的测试环境如何部署吧？如果是这个问题的话可以参考下这篇文档：https://github.com/mipengine/mip2/blob/HEAD/docs/cli/component-deploy.md
