### ISSUE TITLE
mip2 下mip-carousel不支持内部使用自定义标签

### ISSUE THREAD

**Issue by lsh082096** [mipengine/mip2#214]
**BUG 描述**
mip2 下mip-carousel组件使用除mip-img外的html标签如div等,这些dom结构不会被渲染到页面上

**复现步骤**
如下代码，
` <mip-carousel
            defer="1000"  
            layout="responsive" 
            width="600" 
            height="400"
            indicator
            indicatorId="mip-carousel-example"
            >
            <div>1</div>
            <div>2</div>
        </mip-carousel>`

页面将不会渲染mip-carousel内的div

**期望结果**
mip-carousel内部支持自定义结构

**截图**
上述代码生成dom结构
![页面结构](https://user-images.githubusercontent.com/42226451/44644083-6cb28f80-aa05-11e8-8a6d-bb3355387c38.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by craigchencc** [comment]
`mip-carousel`轮播图组件目前支持增加数字指示器，增加副标题，增加翻页按钮等自定义行为，具体使用可查看[官网链接](https://www.mipengine.org/v2/components/builtin/mip-carousel.html)，请问在carousel内部使用自定义标签的目的是什么呢？

**Comment by lsh082096** [comment]
`mip-carousel` 中增加自定义标签是因为有实现翻页横划功能的需求，其交互和样式与`mip-carousel`比较类似，并且mip 1.0中该组件是可以在内部使用自定义标签而不仅仅是只能添加`mip-img`

**Comment by craigchencc** [comment]
感谢提出建议，是本人的代码出问题了，会马上提交pr进行修正的，非常感谢！
