### ISSUE TITLE
申请better-scroll包

### ISSUE THREAD

**Issue by lsh082096** [mipengine/mip2#229]
**要申请的 npm 包名**
better-scroll

**描述一下添加该 npm 包的必要性**
在开发一个mip页，需要实现翻页横划效果，依赖于该npm包。并且该npm包实现可以很多页面滚动的效果，如带弹性势能的横划，和翻页横划效果等，应用场景很广泛

**补充信息**
补充其他信息，如截图等

**Comment by clark-t** [comment]
已增加
