### ISSUE TITLE
mip-shell title 未考虑过长情况

### ISSUE THREAD

**Issue by zhuguoxi** [mipengine/mip2#235]
**BUG 描述**
如图 mip-shell title 未考虑过长情况

**截图**
![image](https://user-images.githubusercontent.com/7043799/44941957-11ecaf80-adda-11e8-8b9b-44218f2e5b72.png)

**Comment by easonyq** [comment]
我尽快修复

**Comment by zhangjunjie02** [comment]
测试通过
测试机型：
iphone4s  iphone5s iphone7p  小米5  华为nova   小米mac2   华为p9
测试的浏览器
UC浏览器   自带浏览器  Safari   手百    Chrome浏览器    简单搜索   qq浏览器
