### ISSUE TITLE
postMessage 数据格式问题

### ISSUE THREAD

**Issue by xiaoiver** [mipengine/mip2#25]
## 问题描述

目前根页面和各个子页面 `<iframe>` 通信使用 `postMessage()`，传递的数据对象是不需要开发者自己序列化的。[MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/postMessage)

但是 `message` 被地图接到之后，不加 `try catch` 直接当做字符串处理，就会报错。
![image](https://user-images.githubusercontent.com/3608471/42197177-26da0168-7eb4-11e8-9fcb-b8cf60e8ac14.png)

**Comment by PengXing** [comment]
这个问题需要谁来修？

**Comment by xiaoiver** [comment]
这个我们通过修改代码暂时避免了。
不过 `JSON.parse` 这种代码还是需要第三方开发人员自己注意，虽然说报错了也就不执行倒不会影响。
