### ISSUE TITLE
IOS的UC和手百下，页面白屏不渲染

### ISSUE THREAD

**Issue by easonyq** [mipengine/mip2#252]
**BUG 描述**
清晰和准确的描述 Bug 是什么
在 IOS的UC和手百下，切换到部分页面时目标页面白屏。
稍微用手指上下滚动，即可恢复正常
**复现步骤**
重新复现 Bug 的步骤
1. 用上述浏览器访问 [https://mip.xin.com/rek4jj5kmg/che53446838.html](https://mip.xin.com/rek4jj5kmg/che53446838.html)
2. 先点击
![image](https://user-images.githubusercontent.com/6800839/45069227-111b8c80-b0fe-11e8-8e8a-87b6e7e32a7f.png)
再点击
![image](https://user-images.githubusercontent.com/6800839/45069236-18db3100-b0fe-11e8-8e7d-cd30db3cfb70.png)
3. 目标页面白屏，稍微上下滑动可恢复正常

**期望结果**
目标页面正常展现

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

我的复现环境是 ios 10 UC和手百均可，safari 没有问题，正常显示。

**Comment by easonyq** [comment]
这个问题其实之前由金融的同事提出过，也进行了临时修补，不想今天又碰上了。

核心在于，目标页面只有一个组件 (mip-xin-params)，且这个组件没有设置 prerenderAllowed。

因此在跳转到目标页面之后，__出于某个原因（例如坐标计算中的兼容性问题）__ 导致 mip 判断这个组件 __不在第一屏__，因此它的所有生命周期都没有运行，自然也没有渲染，就是白屏。

而当滚动一下之后，滚动触发了重新计算，这时 mip 判断它 __在第一屏了__，然后就正常渲染了。

之前金融同事的解决方案是把组件改成 prerenderAllowed: true，但这只能说是缓兵之计，然后这次二手车又碰上了。

我的判断依据是我通过代理，把线上的 mip-xin-params.js 下载到本地，在 `created` 和 `mounted` 两个生命周期中增加了 `alert`，结果到了目标页面白屏时并没有 alert。然后手指上下滑动之后，两个 alert 都出现了，再加上之前金融的问题，让我倾向于这个判断。但具体内核的问题，还是要请 @huanghuiquan 来研究和确认。

**Comment by huanghuiquan** [comment]
经过 debug 发现， 问题产生的原因和 @easonyq 说的一致，建议将 prerenderAllowed 设置为 true 跳过延迟渲染，具体写法为：
```html
<template>
  <div>
    <h1>MIP 2.0 component example</h1>
  </div>
</template>

<style scoped></style>

<script>
export default {
  prerenderAllowed() {
    return true
  }
}
</script>
```
