### ISSUE TITLE
全站 MIP 偶现页面无法滚动 bug

### ISSUE THREAD

**Issue by PengXing** [mipengine/mip2#253]
**BUG 描述**
全站 MIP 偶现页面无法滚动 bug

https://www.mipengine.org/v2/guide/component/introduction.html

来回切换，偶现，页面无法滚动，页面元素可选择，没有透明 mask 盖在页面上

**复现步骤**
页面来回切换，有一定几率复现

**期望结果**
正常滚动

**环境及版本信息:**
 - OS: Mac OS
 - Browser: Chrome 
 - 浏览器 Version: 68

**Comment by xiaoiver** [comment]
是在 PC 上的设备调试模式下么？
