### ISSUE TITLE
需要补充mipengine debug环境使用文档说明

### ISSUE THREAD

**Issue by VenyXiong** [mipengine/mip2#256]
背景：现在为了方便合作方调试，有提供一个https://www.mipengine.org/debug 供开发者进行iframe下环境的验证，但是目前这里的使用文档缺失，并且缺少边界描述，哪些问题可以在这里被自查验证，哪些不能，导致合作方在线下自查效果遇到阻碍，所有的功能验证都需要到线上才能正式回归

**要解决什么问题**
debug环境提供的功能和边界描述，以及不能完成的验收的部分，给出解决方案描述。

**描述一下你理想中的解决方案**
清晰准确的描述你想怎么解决
文档补全
**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

**Comment by easonyq** [comment]
现在 [https://www.mipengine.org/debug](https://www.mipengine.org/debug) 这个环境虽然可以运行，但还有一些问题，主要是：

1. 因为是部署在线上，因此是 https 环境，所以当填入 localhost 或者 http 协议的地址，并使用线下配置是，会遭到浏览器的阻挡。
2. 正如上述所说，文档缺失，描述不明确

鉴于此，我最近已经在开发一个[新的项目](https://github.com/mipengine/mip-cli-plugin-sf)。它是一个 mip-cli 的插件项目，最终将使用 `mip2 sf` 来启动在 localhost，这样就绕开了 https 的那个问题。
至于文档，我会在那个项目中仔细编写，也供各开发者参考。

我打算今天下午先完成最基本的功能（启动服务器，填入 __原始__ URL，查看 SF 环境下的页面）。不过 @zhuguoxi 还提出一个高级需求，我们在完成基本之后，就开始继续吧！也邀请 @VenyXiong 一起加入~~

**Comment by easonyq** [comment]
`mip2 sf` 已经可以工作，相关的用法也可以参考[https://github.com/mipengine/mip-cli-plugin-sf](https://github.com/mipengine/mip-cli-plugin-sf)
