### ISSUE TITLE
中华会计网校IM咨询对接熊掌号申请xzh-sdk白名单

### ISSUE THREAD

**Issue by JordansQ** [mipengine/mip2#273]
**要申请的 npm 包名**
xzh-sdk

**描述一下添加该 npm 包的必要性**
中华会计网校IM咨询对接熊掌号，需使用熊掌号sdk

**补充信息**
请添加 xzh-sdk 到白名单

**Comment by clark-t** [comment]
done

**Comment by JordansQ** [comment]
![image](https://user-images.githubusercontent.com/22501706/45416644-f7a4b280-b6b2-11e8-95d9-aabc1d51f9e2.png)
还是提示xzh-sdk不在白名单

**Comment by clark-t** [comment]
请npm uninstall -g mip2 后重新 npm install -g mip2 即可
