### ISSUE TITLE
MIP2 核心代码是否需要在页面不包含 <mip-shell> 的时候默认加上？

### ISSUE THREAD

**Issue by easonyq** [mipengine/mip2#279]
**要解决什么问题**
这是一个值得讨论的问题。

线上目前包含这个逻辑，即页面不包含 `<mip-shell>` 的时候，会由 mip.js 核心默认加上 `<mip-shell>`（像 `<mip-shell-xiaoshuo>` 这类个性化 shell 不在讨论范围），为的是让所有 MIP2 页面都包含以下功能：

1. 页面切换时的效果
2. 路由管理

但 @Espoir-L  指出，使用 MIP2 应该有 3 个层级：

1. 直接使用 mip2.js，但是不配置 `<mip-shell>`。这种相当于 __只想使用 MIP2 组件开发的 vue 写法等便利，但本质仍然是一个单页，而不是整站__，因此也就不需要页面切换和路由管理功能。
2. 使用 mip2.js，且配置 `<mip-shell>`。这种是既享受开发便利，又需要整站效果。也是目前线上 MIP2 页面的状态。
3. 有自定义逻辑，因此实现了个性化 Shell。这个是小说，极速服务等的状态。

因此在她的设想中，第一种情况不应该默认添加 `<mip-shell>` 标签，而众多不经修改直接从 MIP1 页面迁移到 MIP2 的页面就在此列。且这样也能一定程度上解决 MIP2 跳转到 MIP1 页面的BUG （如 #278 ）。

我其实有点赞同她的想法，但我的疑虑是：__线上是否存在引用了 mip2.js 但是没写 `<mip-shell>` 的页面？__ 如果有，那他们本来拥有的切换功能经过修改就不存在了，不知道是否会引起问题。如果没有，那我觉得这个改动有讨论的价值。

另外一个折中方案是添加一个配置项，但默认值又值得讨论。是默认支持整站，还是默认支持单页呢？

**Comment by PengXing** [comment]
那么在这里需要重新定义一下  MIP-SHELL 的功能，什么是 MIP-SHELL？

目前 MIP-SHELL 所有的功能如下：

- 代理所有链接的点击
- 监控路由的变化
- 负责页面切换动画
- 渲染页面固定部分

而实际上，是不是这些事情都应该由 MIP-SHELL 来承担

确实如 @Espoir-L 所说，MIP1 的页面大多都是不需要渲染页面固定部分的，只需要页面切换动画

基于此，我们把 1. 代理链接的点击 2. 监控路由变化 3. 页面切换动画，移到 mip2.js 核心中，而 MIP-SHELL 这个内置组件只负责渲染页面公用部分，是否可行？

**Comment by easonyq** [comment]
代理链接的点击现在在 `viewer.js` 里面。

监控路由变化和切换页面，最早是在 `page/index.js` 里面的。后来因为要独立 mip-shell 才放入到 shell 当中，因为 shell 的定义是 __能够运行项目的最小集合__，因此当时我们认定路由也是其中的一部分，切换动画也是。

我其实也不建议大规模的去重构 shell，否则线上必然又带来很多问题。我觉得考虑到 @Espoir-L 的需求，其实就讨论2个问题：

1. 是否需要去掉默认补充 `<mip-shell>` 的逻辑。
    如果去掉，那么没有 `<mip-shell>`  标签的页面就不带有路由管理，切换动画和头部。这作为一个单独的页面来说其实是完全合理的，所有我觉得是一个可行&简单的方案。
    当然风险就在我之前说的，会不会存在线上已有的 CASE。不过我的了解好像不太多

2. 如果依然保留这个补充 `<mip-shell>` 的逻辑，第二个问题是是否应该加个“单页配置项”，且默认值是什么。
    保留逻辑的话，通过配置项也可以实现类似 MIP1 的 “单页” 项目。如果把默认值设为单页，其实就和第一条的效果是一样的；如果设为整站，那就跟现在线上的效果一样。如果需要单页的，需要额外加配置项。当然这点对于数量巨大的历史页面迁移会带来不便。

如果重构，重构过后路由，切换和头部散落在不同的地方，反而增加判断逻辑的数量；另外实际上现在统一到 shell 已经是从 page 里面拆过来的；再加上重构本身的成本和线上已经运行的站点，我其实不太建议。我比较倾向的做法是第一条，去掉默认补充 `<mip-shell>` 的逻辑即可。

**Comment by easonyq** [comment]
另外我想到一个事情。 #278 是目前碰到的实际问题：MIP2页面不能跳转到MIP1页面。假如我修好了这个问题，那之后无论是整站，还是单页，无论是否补充 `<mip-shell>` 标签，其实都无所谓吧？而以往那些MIP1的单页，升级成MIP2之后，当中如果还有 `mip-link` 反而能够顺利变成整站，似乎也没有坏处呀？！
