### ISSUE TITLE
移动端适配rem转换问题

### ISSUE THREAD

**Issue by CJ-king** [mipengine/mip2#28]
目前组件在mip2 build过程中样式中的px并没有转换成rem,是否可以统一下转换规则，然后在打包过程中把这个功能添加上？

**Comment by PengXing** [comment]
我觉得 px 是有它的使用场景的，而且应该很多，相反，rem 的使用场景反而没有 px 多，那为什么要将 px 都转成 rem 呢？

现在我们提供的 rem 方案是
1. width 大于 360px 的时候，1rem = 100px
2. width 小于等于 360px 的时候，1rem = 90px

在这个方案中，rem 需要开发者自己根据上面这两个规则来计算
