### ISSUE TITLE
mip-stats-baidu 百度统计组件 data-stats-baidu-obj 要求配置外层为单引号，内层为双引号。

### ISSUE THREAD

**Issue by shao-kang** [mipengine/mip2#282]
mip-stats-baidu 百度统计组件 data-stats-baidu-obj 要求配置外层为单引号，内层为双引号， 这个和代码规范检测冲突， 转码处理又比较麻烦， 不能封装一下吗？

**Comment by PengXing** [comment]
你是指 MIP1 的，还是 MIP2 的？

**Comment by PengXing** [comment]
在 mip2 中，可以通过 `MIP.util.jsonParse` 来格式化 `data-stats-baidu-obj`，就可以支持单引号了，需要迁移 mip-stats-baidu 的同学将 `JSON.parse` 改成 `MIP.util.jsonParse`
