### ISSUE TITLE
中大网校-熊掌号js-sdk npm包白名单申请

### ISSUE THREAD

**Issue by beanLau** [mipengine/mip2#283]
**要申请的 npm 包名**
xzh-sdk

**描述一下添加该 npm 包的必要性**
页面添加咨询功能，组件内部需要引入百度熊掌号js-sdk，调用IM聊天能力。

**补充信息**
无

**Comment by clark-t** [comment]
该 npm 包已在白名单内，请尝试 `npm uninstall -g mip2` 再重新 `npm install -g mip2`
#273

**Comment by clark-t** [comment]
或者将 mip2 升级至最新的 1.3.2 版本即可

**Comment by beanLau** [comment]
> 或者将mip2升级至最新的1.3.2版本即可

现在是线上代码构建时候找不到xzh-sdk包。跟我本地没关系吧？

**Comment by clark-t** [comment]
是的

**Comment by beanLau** [comment]
> 是的

嗯嗯，3q
