### ISSUE TITLE
小说shell添加prerender的预渲染逻辑

### ISSUE THREAD

**Issue by Espoir-L** [mipengine/mip2#284]
**要解决什么问题**
目前小说每次翻页，有较长时间的loading态，比较影响用户体验，而且小说里每页的逻辑是相对独立的，不会涉及到页面间的互相依赖的功能，所以想看下我们如果在mip-shell和小说shell添加小说预渲染的逻辑

**描述一下你理想中的解决方案**
由mip-shell添加api，可以控制预渲染的逻辑，按照大搜现有的prerender去处理，不执行相关的JS代码；当小说shell传入相关配置时，可以提前加载下一页的内容，当翻页时候，下一页不加loading态的切换页面划入；

**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

**Comment by easonyq** [comment]
我的想法是这样
1. page 提供一个方法（通过 `window.MIP` 能够调用的到的那种）。当页面调用时，把要预渲染的目标页面的 URL 传入
2. 根据 #69 的方案，在加载 iframe 的时候，添加一个 hash: `#prerender=1`，从而阻断所有组件的生命周期
3. 正式切换页面时，通过 `<a mip-link>` 上添加一个特殊属性或者 `viewer.open` 添加一个特殊参数来表示目标页面已经预渲染过了
4. 在切换页面时，如果有 3 里的特殊标识，不创建新的 iframe 而是寻找已有的，并向其 `postMessage` 告知从预渲染状态切换到正常状态，再直接动画展现，期间不展现 loading

基本就是这么一个流程。但依赖 #69 上线，因为 mip.js 核心中对 prerender 的处理还是需要先上线的。

**Comment by Espoir-L** [comment]
根据现有的方案，存在这样的问题，因为预渲染会阻断组件的生命周期，但是在mip-shell-xiaoshuo的less里面功能是通过前端缓存取用户自己的设置项，比如字体，主题等，然后去修改当前页的字体大小，按照现有的方案，会在翻页的时候，出现页面闪动的问题，感觉需要考虑下这个点；

**Comment by easonyq** [comment]
我理解预渲染只是让组件不执行生命周期，但JS是实际加载的，因此CSS也是会被加载的。@huanghuiquan

**Comment by huanghuiquan** [comment]
还有一种方式，就是给标签加上 prerender 属性 `<mip-shell-xiaoshuo prerender></mip-shell-xiaoshuo>`，让生命周期不受阻塞
