### ISSUE TITLE
MIP  与  AMP 的差异对比及可改进部分讨论

### ISSUE THREAD

**Issue by ccksfh** [mipengine/mip2#288]
## 背景
AMP 发展到现在，在加速技术、组件建设方面做了很多事情，而 MIP 在很多方面都落后于 AMP（当然，MIP2 中出现了不少有别于 AMP 的一些升级），还停留在一开始启动这个移动网页加速项目的时期，这个 issue 旨在列出一些 AMP 中表现优异而 MIP 没有的规范/技术/组件等，MIP 将以此为目标，不断完善自己，向 AMP 看齐。

欢迎大家关注，请自由地在此 issue 下跟帖提出自己的意见或补全这份 diff，并积极地参与到其中。

**Comment by ccksfh** [comment]
## Core

### AMP Boilerplate Code 样板代码
`<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>`

简化：

```html
<!-- 8s 后由 visibility -> visible -->
<style amp-boilerplate>
   body {
     animation: -amp-start 8s steps(1, end) 0s 1 normal both
   }
   @keyframes -amp-start {
     from { visibility: hidden }
     to { visibility: visible }
   }
 </style>
```

amp.js ready 后移除animation， 设置为 visibility: visible

### AMP.BaseElement 组件生命周期
生命周期比 MIP.CustomElement 多很多

如：`preconnectCallback`、`createPlaceholderCallback` 等等 
https://github.com/ampproject/amphtml/blob/master/contributing/building-an-amp-extension.md#baseelement-callbacks

**Comment by ccksfh** [comment]
## 校验

### 页面校验
- Web Interface
- Browser Extension
- NPM Packages for CI
- Browser Developer Console 
- 通过添加hash #development=1, 可以直接在控制台输出不符合规范的 warning 
https://www.ampproject.org/static/img/docs/validator_errors.png
![e6974a47ff715b52b27d6fe791ff3d9d537636b7](https://user-images.githubusercontent.com/4878697/45733115-f541db80-bc11-11e8-9870-0f10e3405e23.png)


### 组件校验规则
统一通过 *.protoascii 编写规则 
https://github.com/ampproject/amphtml/blob/master/contributing/component-validator-rules.md

**Comment by ccksfh** [comment]
## 基础建设
- [x] AMP Validator
- AMP By Example 完善的组件例子
- AMP Playground 在线代码编辑和展示
  - MIP 也[有](https://www.mipengine.org/validator/preview)，但是只能通过提交 url 的方式，不能在线构建页面
- AMP Start： AMP 模板 + 组件库
- AMP Experiments:  新特性实验
- AMP Toolbox 
  - amp-optimizer: a javascript library implementing server-side-rendering for AMP pages.
  - amp-optimizer-express: an express middleware that applies AMP server-side-rendering on the fly.
  - amp-runtime-version: a javascript library for querying the current AMP runtime version.
  - amp-cache-list: a javascript library for listing the known AMP Caches.
  - amp-update-cache: a javascript library for updating AMP documents in AMP Caches.

## 社区建设
- [x] 官网
  - MIP 中规范依然不够明确，如CSS: 哪些特性不可用，用什么方案替代，没有一个独立文档可查阅
- [ ] CMS 构建页面（AMP 多由各种第三方来建设）
- [x] 讨论区
  - MIP：QQ群、github issue
- [ ] The Latest
  - 包括 blog、组件更新、AMP 相关活动动向，roadmap，订阅功能等
  - MIP只有组件升级动态
- [ ] AMP 甚至有详细文档教小白怎么提 pr 做贡献

## 其他

### PWA
MIP 在官网没有体现
- 入口在 mip-cli 的文档里，而且目前只涉及到了 sw 和 app-shell

### AMP for email 
使用 AMPHTML 编写邮件，结合 GMail
- rules + 有限组件
- amp 子集 - 出于安全考虑
- 没有 amp-cache

### 对跨域/CORS 有独立章节详细教学
  - MIP 目前好像只在 mip-bind 章节提及到
  - 感觉 AMP 信息比较全面

### lighthouse / best practise

### non-AMP page 通过 link 指向对应 AMP page

### SEO
使用结构化数据让主流搜索引擎(google、bing、yahoo 等)更懂你的页面
`<script type="application/ld+json"></script>`

利于 SEO （我们的搜索引擎是否支持？）

**Comment by ccksfh** [comment]
## 加速规范
- []

**Comment by hacke2** [comment]
神马这边看了下，以下两个组件感觉较容易实现，可以试着练练手

- amp-selector
- amp-mathml

另外一些需要 UC 这边的特性的组件，我们这边也可以一起共建，比如分享

**Comment by PengXing** [comment]
@hacke2 那神马的同学看看实现一下 amp-selector 和 amp-mathml 练练手吧，有什么需要帮助的，可以随时找我

- [ ] amp-selector
- [ ] amp-mathml

**Comment by PengXing** [comment]
整理了一下大致 MIP 需要做的事情有如下：

- [ ] 整理 MIP 文档，分初级和高级用法两部分
- [ ] 同步 layout 支持的 media, sizes, heights 等属性，梳理和规范化 MIP layout
- [ ] mip-iframe 增加 HTTPS 链接的校验
- [ ] amp-3d-gltf
- [ ] amp-fx-flying-carpet
- [ ] amp-fx-collection
- [ ] amp-date-picker
- [ ] amp-selector
- [ ] amp-user-notification
- [ ] amp-animation
- [ ] amp-date-countdown
- [ ] amp-fit-text
- [ ] amp-font
- [ ] amp-mathml
- [ ] amp-pan-zoom
- [ ] amp-timeago
- [ ] amp-viz-vega => mip-viz-echarts

**Comment by PengXing** [comment]
这个 ISSUE 关了，后续状态请参照 ISSUE #303
