### ISSUE TITLE
华为荣耀8、OPPO手机横滑不了

### ISSUE THREAD

**Issue by lunaticYoung** [mipengine/mip2#289]
**BUG 描述**
在访问 https://m.baidu.com/wishwing/c/s/mip.moretickets.com/index.html 页面的时候顶部分类菜单第一次进入无法左右滑动，在点击一次分类类目以后滑动才可以使用，如果单独访问 https://mip.moretickets.com/index.html 页面是没有问题的，会复现此bug的机型包括：华为荣耀8、OPPO等安卓机器。

**复现步骤**
重新复现 Bug 的步骤
1、通过简搜访问 https://m.baidu.com/wishwing/c/s/mip.moretickets.com/index.html 
2、滑动顶部分类导航菜单

**期望结果**
在简搜、QQ浏览器或其他浏览器中访问都可以正常滑动

**环境及版本信息:**
 - 华为荣耀8手机
 - OPPO 手机
 - qq手机浏览器

**Comment by easonyq** [comment]
我能够复现这个问题，但我研究了一阵子，没能找出具体出问题的 CSS 或者 DOM 结构究竟在哪里，我个人比较倾向于是 mip 核心和 SF 的代码共同触发了浏览器的某个 BUG。

不过在众多次尝试中，我发现了一个不太完美的解决方法：

把 `.type-nav` 元素的 CSS 默认设置成 `opacity: 0.99`，然后使用 JS 去 __延迟设置__  `opacity: 1` 即可。原理是让浏览器重绘这个元素即可。因此在 SF loading 还未消失的情况下就设置 `opacity` 会失效，必须等到 loading 隐藏，实际元素展现到了页面上再进行这个操作才能生效。

考虑到这个特性，建议使用 setInterval，在页面展现的前2秒或者3秒，每隔一段时间来回设置一次，触发重绘。

我会和 SF 的同学继续探寻原因，以求找到最好最彻底的修改方法。

**Comment by easonyq** [comment]
另外 @zhuguoxi @oott123 我写了一个简单的页面，使用 `mip-fixed` 内部嵌套一个可以横向滚动的列表（模仿摩天轮票务，使用 `white-space: nowrap`, `display: inline-block` 和 `overflow-x: auto` 等）：

* 直接打开，是正常的
* 使用最简单的 iframe 打开，也是正常的
* 使用 SF 环境打开，无法滚动

最后，我把线上的摩天轮票务的 mip cache 的页面使用一个简单的 iframe 嵌入，即：
```html
<iframe src="https://mip-moretickets-com.mipcdn.com/c/s/mip.moretickets.com/index.html#mipanchor=&isTitle=null&canClose=true"></iframe>
```
也是正常的。

所以我觉得问题出在 SF 里面的可能性更大一些，要麻烦两位排查了。
