### ISSUE TITLE
刷新返回，iframe依旧存在

### ISSUE THREAD

**Issue by jenkey2011** [mipengine/mip2#29]
- 类型：bug
- 概率：必现
- 复现：`页面A`跳转至`页面B`，刷新`页面B`，返回至`页面A`，页面A B 同时存在
### 操作如图：
![2018-07-09 17_08_31](https://user-images.githubusercontent.com/20010737/42441916-e237f4b0-839b-11e8-99ba-b8a40ff9d9b2.gif)

**Comment by xiaoiver** [comment]
确实是一个 Bug，应该是刷新之后返回，没有隐藏原始页面中除了 shell 之外的内容。
