### ISSUE TITLE
MIP 官网及文档整理

### ISSUE THREAD

**Issue by PengXing** [mipengine/mip2#291]
现在 MIP2 官网文档揉在一起，对于接入 MIP2 的初学者非常不利，因此需要再进行更细致的划分以及进行一些补充，需要进行修改和补充的点，我列在下面，整体会改为和 AMP 官网类似，有条理且清晰

文档需要分成两个部分，mip 的使用和 mip 组件开发，目前现有的文档这两块内容是杂糅在一起的，阅读起来非常困难，mip 页的开发者并不需要过多关心 mip 内部机制。目前我已经列出了基本的文档目录大纲，大家根据自身情况挑选相应的部分进行整理。在整理文档的时候，需要做几件事情：

1. 校勘文档内容是否正确（图片、链接、文档内容是否与目前的 MIP 情况相一致）
2. 分离 mip 的使用方法和 mip 内部机制
3. 缺少的文档章节自行补充，并在下面的目录补充相应的条目

## MIP 文档目录

- [ ] 关于 MIP
  - [x] 什么是 MIP
  - [x] MIP 如何运作的
  - [x] MIP 适用场景 @PengXing 
  - [x] MIP 内容声明
  - [ ] Showcases
  - [ ] 小故事
- [ ] 学习
  - [ ] 教程
    - [x] 起步 @craigchencc 
      - [x] 新手指南（技术导览）
      - [x] 开发您的第一个 MIP 页面（要求能够展示自定义样式、组件使用、on 机制、mip-bind，循序渐进）
      - [x] 调试与验证 MIP 页面
      - [x] MIP 搜索生效
    - [x] 开发规范
      - [x] MIP-HTML 规范
      - [x] MIP-Cache 规范
      - [x] Canonical 使用规范
      - [x] MIP 校验规则
      - [x] MIP 内容声明
    - [ ] 样式与布局 @craigchencc 
      - [x] 样式和布局（章节概述）
      - [x] 支持的 css （需要写到 `<style mip-custom>` 里）
      - [x] 组件布局（layout）
      - [ ] 媒体查询（media srcset heights sizes）@huanghuiquan
      - [ ] 占位符和备用行为（placeholder 和 fallback）@huanghuiquan
    - [ ] 交互式设计 @clark-t 
      - [x] 交互式设计介绍
      - [x] 事件机制（讲 on 机制）
      - [ ] 数据驱动
         - [ ] 数据驱动流程介绍（包括 mip-data 定义、MIP.setData、m-bind 的从定义到触发展示全流程）
         - [x] mip-data 定义
         - [x] MIP.setData getData watch
         - [x] 数据绑定语法说明
         - [x] class 与 style 属性绑定语法说明
      - [x] 自定义 JS (讲 mip-script，可简单提 mip-sandbox 严格模式)
    - [x] 全站 MIP 开发
      - [x] 介绍
      - [x] 全站 MIP 页面编写规范
      - [x] 页面切换方案
      - [x] Page API
      - [x] MIP Shell
      - [x] MIP Viewer
      - [x] MIP 快捷方式
    - 用户行为统计与分析 (@Ricardo-Li  )
      - [ ] 概述
      - [ ] mip-pix
      - [ ] mip-analytics
    - 渐进增强式设计
      - [ ] MIP 页离线可用（mip-cli 生成 service worker 与 mip-install-serviceworker 的使用）
    - [x] 辅助开发工具 (@easonyq )
      - [x] 介绍
      - [x] mip cli 用户自定义扩展介绍 @chenqiushi 
      - [x] mip-cli-plugin-sf 使用说明
      - [x] mip-cli-plugin-site 使用说明
  - [x] API
    - [x] 全局 API
    - [x] 工具 API
  - [x] Codelab
- [x] 组件 @clark-t @craigchencc @liuruoran88 
  - [x] 组件列表
    - [x] 布局
    - [x] 呈现
    - [x] 媒体
    - [x] 动态内容
    - [x] 广告
    - [x] 社交
    - [x] 统计
  - [x] 贡献组件代码
- [x] 工具
  - [x] MIP 代码校验工具
  - [x] MIP 效果预览工具
  - [x] MIP PATH 转换工具
  - [x] MIP-CLI 本地开发工具
- [ ] 最新动态
  - [ ] 最新内容 @clark-t 
  - [ ] 路线图 @clark-t 
  - [x] 官方博客

## MIP 组件开发目录

MIP的使用与组件开发是两回事，因此将组件开发的内容独立出来

- [ ] 贡献组件代码
  - [x] 起步 @chenqiushi 
    - [x] 如何贡献组件代码（介绍如何 fork 官方组件仓库、提交 PR 规范这些）
    - [x] 组件开发规范
    - [x] 使用 MIP-CLI 开发组件
  - [x] 组件开发 @clark-t 
    - [x] 组件写法（Vue 和 Custom Element    两种）@yenshih
    - [x] 资源管理
    - [x] 父子组件机制
    - [x] 模块异步加载
    - [x] 测试代码替换（process.env.NODE_ENV 和 proxy 配置）
  - [x] 组件调试 @clark-t 
    - [x] 组件调试（mip2 dev）
    - [x] 组件联调（单独成章用于强调 mip2 dev -a）
    - [x] mock 数据
  - [x] 组件部署 @chenqiushi 
  - [x] 组件机制 @chenqiushi 
    - [x] MIP 组件化介绍
    - [x] MIP 组件和 Vue 的关系（有点奇怪）
    - [x] 组件实例的生命周期和回调钩子
    - [x] 组件属性与数据传递
    - [x] 事件机制与组件通信
    - [x] 组件插槽
    - [x] Service 机制 @yenshih 
    - [x] 沙盒机制 @clark-t 
  - [x] 工具库
    - [x] 视图信息 viewer 与 viewport
    - [x] 与服务端通信（fetch fetch-jsonp）
    - [x] naboo 动画库
    - [x] gesture 手势集合
    - [x] platform 识别
    - [x] hash 通信机制

**Comment by chenqiushi** [comment]
暂时先在 dev-rebuild-docs 分支，进行文档结构和内容的整理
