### ISSUE TITLE
部分API中依赖CDN域名识别的问题

### ISSUE THREAD

**Issue by tayqassqan** [mipengine/mip2#296]
**要解决什么问题**
MIP被其他CDN Cache使用时候（神马CDN），当前部分API：isCache、getOriginUrl。

**描述一下你理想中的解决方案**
CDN域名识别在核心代码中统一维护

**Comment by zidanDirk** [comment]
iframe-shell的loader.js中 mipCacheUrl 目前是 '//mipcache.bdstatic.com/c/'，后期可能需要统一修改一下

**Comment by tayqassqan** [comment]
> iframe-shell的loader.js中 mipCacheUrl 目前是 '//mipcache.bdstatic.com/c/'，后期可能需要统一修改一下

对的，iframe-shell的project我也加一下issue

**Comment by PengXing** [comment]
神马的 CDN Cache 的规则是怎样的？让神马的同学自己提 PR 解决吧

**Comment by wqllpw** [comment]
https://github.com/mipengine/mip2/blob/dev/packages/mip/src/mip1-polyfill/index.js#L23
包含依赖的外部代码，是baidu或者mipcdn域名，可能需要通过编译来替换解决
