### ISSUE TITLE
mip-img的popup轮播图中desktop和mobile的效果应做出区分

### ISSUE THREAD

**Issue by craigchencc** [mipengine/mip2#304]
**要解决什么问题**
清晰准确的描述要解决什么问题 

大图浏览下，图片长度明显大于宽度，在desktop下，宽度依然充满整个屏幕导致体验不好。

**描述一下你理想中的解决方案**
清晰准确的描述你想怎么解决

做出区分

**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

https://www.mipengine.org/v2/guide/component/instance-life-cycle.html  
目前效果可看链接中最后的生命周期图

**Comment by PengXing** [comment]
一句话，就是 `contain`..

**Comment by craigchencc** [comment]
`contain` 在我的理解中，就是图片本身的高度宽度比与屏幕的高度宽度比进行比较，根据比较的结果设置图片的高度或宽度为 __100%__ 。

而 `mip-carousel` 这个组件下的图片一般是同一高宽比，但是大图浏览的情况会有不同高宽比的图片，所以可能每次滑动都需要调整 `mip-carousel` 的高度或宽度为 __100%__ 。这样的体验可能会比较好。
