### ISSUE TITLE
开源静态资源及编译模块

### ISSUE THREAD

**Issue by PengXing** [mipengine/mip2#306]
内部还有部分模块需要开源，包括如下：

- 静态资源模块，包括 jquery.js zepto.js 等非组件和核心的静态文件，内部地址为 http://gitlab.baidu.com/MIP/mip-static 
- 编译打包模块，可能并不需要开源整个模块，但是编译打包的代码需要重新梳理一下

**Comment by tayqassqan** [comment]
已同步到： https://github.com/mipengine/mip-assets

**Comment by chenqiushi** [comment]
编译打包的脚本开源整理在 [https://github.com/mipengine/mip-build-pack](https://github.com/mipengine/mip-build-pack)

**Comment by chenqiushi** [comment]
去掉了内网相关的脚本，已同步整理。
