### ISSUE TITLE
返回无切换效果

### ISSUE THREAD

**Issue by zhuguoxi** [mipengine/mip2#31]
MIP.viewer.page.back() 执行返回页面无切换效果
头部返回正常

**Comment by easonyq** [comment]
这个是我们特意去掉的，但这个问题我们可以在这里讨论一下。

一开始我们所有的切换/前进/后退都有动画。但后来发现可能有些浏览器在点击前进后退或者手势时会有自己的动画，再加我们的动画就有重复的问题出现，因此改成了 __只有点页面的 `<a>` 或者后退才有动画__，所以 API 调用也被划到了没有动画的那一类里面。

**Comment by zhuguoxi** [comment]
back api 也应该是属性程序内的操作，所以是不是认为跟头部返回是一样

**Comment by easonyq** [comment]
倒也是可以，那这个今天改一下
