### ISSUE TITLE
exports MIP 导致报错

### ISSUE THREAD

**Issue by huanghuiquan** [mipengine/mip2#312]
**BUG 描述**
由于 mip 打包后产生的是 umd 的格式的代码：
```
!function (e, t) {
    "object" == typeof exports && "undefined" != typeof module 
        ? module.exports = t()
            : "function" == typeof define && define.amd 
            ? define(t) : e.MIP = t()
}(this, function () {
    // mip 代码
    /// MIP = {...}
    return MIP
})
```
由于 页面既不是使用 amd 也不是 cmd 的工具，最后会执行 window.MIP = t()，也就是直接把 MIP 挂到 window 下，然而现在的组件执行依赖 `waitDocumentReady` 执行后才可以执行，判断的方式如下：
```js
(window.MIP = window.MIP || []).push({
    name: "mip-stats-sa",
    func: function() { // 组件代码
    }
})
```
如果mip加载好了，但是 waitDocumentReady 回调还没触发，就会导致部分组件依赖 waitDocumentReady 的代码报错

**复现步骤**
无

**期望结果**
去除 export MIP，避免在 waitDocumentReady 之前 MIP 直接挂载到window下

**Comment by easonyq** [comment]
> 去除 export MIP，避免MIP挂载到window下
这……

**Comment by huanghuiquan** [comment]
@easonyq 表述不太准确，改了
> 去除 export MIP，避免在 waitDocumentReady 之前 MIP 直接挂载到window下

**Comment by easonyq** [comment]
因为 shell 组件是打包在 mip.js 内部的，所以我想请问一下，在 shell 组件的哪些生命周期在 waitDocumentReady 之前，哪些在之后？

**Comment by huanghuiquan** [comment]
@easonyq 所有的组件都是在 waitDocumentReady 回调里执行的
