### ISSUE TITLE
小说shell中支持无限下拉

### ISSUE THREAD

**Issue by apple01150525** [mipengine/mip2#321]
**要解决什么问题**
小说shell中支持无限下拉布局方式
改变原有的翻页阅读方式，阅读方式改为无限下拉样式，方便读者进行沉浸式阅读
**描述一下你理想中的解决方案**
将现有iframe的position布局改变为垂直方向布局，由mip-shell添加以下4个api，支持改变现有布局方式 
       - 创建iframe
       - 删除iframe
       - 更新路由
       - 获取iframe
**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

**Comment by easonyq** [comment]
我在 dev-xiaoshuo 分支上进行了开发，目前提供了一些方法来满足如上的需求，如下：

## 创建 iframe

因为根据业务需求，小说是要创建**预渲染的**页面，因此这部分正好和 #284 一致，所以直接使用那边的方法就可以了，语法如下

```javascript
window.MIP.viewer.page.prerender([
  'http://localhost:8080/page1.html',
  'http://localhost:8080/page2.html'
]).then(iframes => {
  // 预渲染成功的 N 个 iframe DOM
})
```

注意：

1. 不能使用跨域的地址

2. 必须把地址写全，即协议，域名，端口号等，不能使用相对路径 OR 绝对路径

## 获取 iframe

因为涉及删除 iframe 和设置位置，所以不免要使用到获取 iframe 容器的操作。page 本次也提供了这个方法

```javascript
let iframe = window.MIP.viewer.page.getIFrame(pageId)
```

## 删除 iframe

默认的 Shell 内核逻辑是在每次创建 iframe 时都会自动检测是否达到最大值，并从中选择一个删除。但这个方法位于 page 对象中，并不在 Shell 中，因此不能提供继承，从而导致子类改写是不可能的。为此我的方案是：

1. 在创建 iframe 时（例如本例中的 `prerender` 方法）添加参数，示意不要进行内置的删除方法，暂时忽略 iframe 最大数量限制

2. 创建完成后（例如在例子中的 `then` 内部）由业务方决定如何选择要删除的 iframe。

对应到代码，在调用 `prerender` 方法时，额外传递一个参数；在 `then` 内部，额外处理删除逻辑。可能会用到的变量或操作如下。

```javascript
let page = window.MIP.viewer.page
page.prerender([urls], {ignoreIframeMaxNum: true}).then(iframes => {
  console.log(page.MAX_PAGE_NUM) // 当前是 6，可能会用到

  for (let i = 0; i < page.children.length; i++) {
    let currentPage = page.children[i]
    // 如果满足某些条件，选中了某个 iframe 的话，删除操作如下：
    // 注意：绝对不能删除当前页面，必须谨慎操作！
    if (condition) {
      let iframe = page.getIFrame(currentPage.pageId)
      if (iframe.parentNode) {
        iframe.parentNode.removeChild(iframe)
        page.children.splice(i, 1)
        break
      }
    }
  }
})
```

## 更换当前路由而不触发重绘

添加额外参数 `skipRender` 实现。

```javascript
window.MIP.viewer.page.replace(url, {skipRender: true})
```

**Comment by easonyq** [comment]
最终采用的方案没有使用到上述方法，因此对核心来说改动仅仅是对于断网情况下的 iframe 的一个容错。
目前已经上线。
