### ISSUE TITLE
显式声明 MIP 组件依赖

### ISSUE THREAD

**Issue by clark-t** [mipengine/mip2#327]
**要解决什么问题**
目前部分 MIP 组件存在依赖关系，比如 mip-list 依赖 mip-mustache，需要 mip-mustache 先加载完成之后再去加载 mip-list。简单通过 script 标签的书写顺序能解决问题，但明显不够优雅，也不利于各种资源加载优化方案的展开。因此需要在组件代码中新增配置，去显式声明组件依赖关系，由 MIP 核心去读取配置文件，控制组件的加载顺序。

**描述一下你理想中的解决方案**
在组件文件夹下新增 `meta.json` 文件，需要定义 `deps` 字段。如 mip-list 依赖 mip-mustache，那么对应的 meta.json 为：

```json
{
  "deps": [
    "mip-mustache"
  ]
}
```

在编译 mip-list 的时候，将生成类似的代码：

```javascript
(window.MIP = window.MIP || []).push({
  name: 'mip-list',
  func: function () {/* 组件代码 */},
  deps: ['mip-mustache']
})
```

然后修改 MIP.push() 方法去读取 deps 来控制组件的加载顺序。

**Comment by PengXing** [comment]
如何兼容 MIP1 的页面，MIP1 的组件不会编译出带有 `deps` 的代码

**Comment by yenshih** [comment]
MIP1 还是需要额外在 `meta.json`  声明依赖，这个想过确实没办法

**Comment by Espoir-L** [comment]
这个方法在小说的场景里会存在性能上的问题，因此需要核心代码提供可以监听组件之间是否注册成功的事件回调，以便进行业务代码的编写
