### ISSUE TITLE
多层 iframe postMessage 时传递的 event.data.name 不正确

### ISSUE THREAD

**Issue by oott123** [mipengine/mip2#328]
在 iframe 向主文档或者上层 iframe postMessage 时，我们约定了一个 `data.name` 参数，用以区分发送事件的文档或 iframe。

当在搜索结果页(A)使用 superframe 打开 mip2 页面(B)，再在 B 页面打开一个 C 页面（如翻页等）。在 C 页面向 top （即 A）发送消息时，其 name 不正确。

![](https://user-images.githubusercontent.com/905663/47778273-73c18b00-dd31-11e8-8e84-bde95a3d6474.png)

预期：`iframe-shell-????`

得到：mip2 的一个 json

问题：

当上层文档收一个不能识别的 name 时，它会将这个事件广播给所有 messenger。而预渲染情况下，同时存在两个 messenger ，故导致事件被错误触发。

**Comment by easonyq** [comment]
现在会给子页面传递一个 `rootName`，值就是 SF 打开的第一个 iframe 的 `window.name`，形如 `iframe-shell-xxxxxx`。因此无论是 MIP 的首个页面 (rootPage) 还是后续页面，发送给 SF 的消息的 name 都是这个值。

另外考虑到后续有可能要使用它，我也挂到了全局，通过 `window.MIP.viewer.rootName` 获取，每个页面都可以获取到。
