### ISSUE TITLE
直接引用mip2-extentions 编译产出的组件js地址，执行报错

### ISSUE THREAD

**Issue by VenyXiong** [mipengine/mip2#34]
复现步骤：
1. 单独部署一个mip2页面的服务, 创建一个页面a.html 地址：127.0.0.1:8080/a.html
2. mip2-extentions 里执行mip2 dev
3. 找到测试组件的url地址：127.0.0.1:8111/mip-example/mip-example.js, 写进页面a.html
4. 预览a.html, 页面报错
![image](https://user-images.githubusercontent.com/3196280/42494333-9137332a-8452-11e8-8b11-c44d210b22ba.png)

**Comment by jenkey2011** [comment]
https://github.com/mipengine/mip2/blob/HEAD/docs/cli/component-deploy.md

**Comment by PengXing** [comment]
更新一下 mip2 cli

```
npm i -g mip2 --registry=http://registry.npm.taobao.org
```

**Comment by clark-t** [comment]
已修复 请更新至 mip2@1.1.7
如果html服务器和mip-cli起的js服务器不在同一台机器上，请在启动 dev 时指定 --asset 参数，比如：

```shell
mip2 dev --asset http://192.168.0.10
```
这样就可以通过 `<script src="http://192.168.0.10:8111/mip-example/mip-example.js">` 引入 js 啦
相关文档清参考：
[组件调试](https://github.com/mipengine/mip2/blob/master/docs/cli/component-testing.md#%E5%BC%95%E7%94%A8%E6%96%B9%E5%BC%8F)
