### ISSUE TITLE
npm 包白名单申请

### ISSUE THREAD

**Issue by roccoliu** [mipengine/mip2#342]
**要申请的 npm 包名**
crypto-js

**描述一下添加该 npm 包的必要性**
后端出入参需要，故前端需要用到对应的加解密方法

**补充信息**
无

**Comment by PengXing** [comment]
现在浏览器的支持已经比较完善了，可以看下面的列表，MIP 要求支持的设备版本范围都在，包括 iOS 8+ 和 Chrome 48+，如果真的需要 crypto-js，可以列一下哪些问题是 Web Cryptography 解决不了的

![image](https://user-images.githubusercontent.com/527244/48655278-e92a9c80-ea4f-11e8-83c4-c28affa7cf89.png)
