### ISSUE TITLE
缓存 viewport 宽高值

### ISSUE THREAD

**Issue by huanghuiquan** [mipengine/mip2#380]
**要解决什么问题**
window.innerWidth 和 window.innerHeight 的获取会导致 reflow，影响性能

**描述一下你理想中的解决方案**
缓存 window.innerWidth 和 window.innerHeight 值，在 resize 事件中更新缓存值

**Comment by PengXing** [comment]
该问题属于 #314 的子集，这里先把这个 ISSUE 关掉，后续关注 #314 的进度即可
