### ISSUE TITLE
预渲染事件组件阻塞造成 window.onload 等事件不触发

### ISSUE THREAD

**Issue by Ricardo-Li** [mipengine/mip2#384]
**BUG 描述**
某些组件在 build 中对 `window.onload`，`DOMContentLoaded` 等事件监听做一些操作。预渲染时阻塞了组件 build，并且预渲染阶段已完成 `window.onload` 等事件的触发，造成后续组件渲染时事件监听失效。

**Comment by oott123** [comment]
组件本身不应当假设自己在 onload 之前加载完成，属于组件 bug。组件应当自己处理这个问题，比如判断 readystate，发现没 load 再来 onload。

**Comment by PengXing** [comment]
应该由 MIP 提供统一的接口，再统一把组件全部修改为唯一的接口

**Comment by PengXing** [comment]
@oott123 现在这么说已经没用了，第三方提交的组件存在大量的这种逻辑，而且，JS 还是动态从第三方站点加载的，基本无法解决
