### ISSUE TITLE
script async 影响 DOMContentLoaded 事件监听

### ISSUE THREAD

**Issue by Ricardo-Li** [mipengine/mip2#387]
如果使用 <script async> 加载 MIP 核心和组件，DOMContentLoaded 事件在脚本执行前触发，如果核心或组件有对该事件监听，会造成无法触发的问题。

目前发现的影响包括：
1. 性能日志的发送，性能统计采集了 DOMContentLoaded 时机。
2. MIP1 30多个 站长组件

可参考：https://zhuanlan.zhihu.com/p/25876048

**Comment by PengXing** [comment]
和 #384 似乎是同一类型的问题，这里我先把这个 close 了
