### ISSUE TITLE
【MIP】mip-fixed 元素包含换行符和子元素的情况下会被手百强制隐藏

### ISSUE THREAD

**Issue by clark-t** [mipengine/mip2#389]
**BUG 描述**
对于部分机型的手百，打开 MIP 页面如果存在 `<mip-fixed>` 元素，并且该元素满足以下两点：
1. 包含换行符
2. 包含子元素

手百会强制往该节点增加样式进行节点隐藏：

```
;visibility: hidden !important;height:0px;overflow:hidden !important;
```

事实上经测试后发现，只要是 `position: fixed` 的元素，满足以上两个条件都会被手百干掉，无论是首屏 HTML 就存在 mip-fixed 及其内容，或者是一次性往某个节点 innerHTML 插入 mip-fixed 及其内容都会触发这个机制；

**复现步骤**
重新复现 Bug 的步骤
1. 小米 MIX2S、三星 GALAXY S8
2. 下载最新手百
3. 准备简单的 HTML 即可：

```html
<!DOCTYPE html>
<html mip>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <title>MIP page</title>
    <link rel="canonical" href="对应的原页面地址">
    <style mip-custom>
      .hehe {
        height: 100px;
        width: 100%;
        background: #dcdcdc;
        position: fixed;
        bottom: 0;
      }
    </style>
  </head>
  <body>
  <div id="abc"></div>
  <script>
    var wrapper = document.getElementById('abc')
    wrapper.innerHTML =
    `<div class="hehe">
      <p>哈哈哈哈</p>
    </div>`
  </script>
  </body>
</html>
```

4. 页面并没显示 哈哈哈哈

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by huanghuiquan** [comment]
这是手百的广告屏蔽 feature，后续向手百申请 mipcdn.com 白名单
