### ISSUE TITLE
mip-shell 切换时，右上角样式有抖动现象

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip2#39]
gif：
![323cdd1d8c6f17ae3a7201358f402b68](https://user-images.githubusercontent.com/8498677/42511351-372806a2-8484-11e8-808f-dc281d89ef19.gif)

截图：
![f32c7a7d2611714f6bc8450ec2cbcb68](https://user-images.githubusercontent.com/8498677/42511352-375fe3ec-8484-11e8-8e7a-c1530f864b1f.png)

**Comment by easonyq** [comment]
我会尽快修复~感谢反馈

**Comment by easonyq** [comment]
已经修复，并提交到主干 & 发布到 BOS 了。
另外提醒一点，BOS的地址是 http://bos.nj.bpc.baidu.com/v1/assets/mip/projects/mip.js （有 v1）
并不是你环境中的 http://bos.nj.bpc.baidu.com/assets/mip/projects/mip.js
