### ISSUE TITLE
提个建议，我们的组件文档可不可以加上一些demo 可以在文档中直接看到组件效果

### ISSUE THREAD

**Issue by shao-kang** [mipengine/mip2#40]
我们可以在组件文档平台中添加一些demo ，方便使用者查找组件
可参考下https://cinwell.com/vuep/#/ 这个文档平台，带有demo 在线实时编译的的文档，可以提升文档阅读者的体验

**Comment by PengXing** [comment]
这个会在官网中实现，要过一阵子
