### ISSUE TITLE
非同源导致 javascript error 收集信息不足

### ISSUE THREAD

**Issue by Ricardo-Li** [mipengine/mip2#411]
为了对异常进行监控和上报，目前在 `mip.js` 中进行了 js error 收集。然而由于浏览器在同源策略限制，所产生的 error 无法获取，只能收集到无意义的 `Script Error.`

例如在 `https://m-meishichina-com.mipcdn.com/xxxx` 页面中，引用组件 `https://c.mipcdn.com/static/v1/mip-sidebar/mip-sidebar.js` 发生报错，页面和组件并不同域，收集不到有意义信息。
![image](https://user-images.githubusercontent.com/7337097/49790045-47ede800-fd68-11e8-835b-28d9bf91c960.png)

方案：推进支持 CORS？

**Comment by PengXing** [comment]
这个可以推进，只需要修改 mipcdn 的返回头，会不会有潜在的风险，虽说 mipcdn 上都是静态文件

**Comment by Ricardo-Li** [comment]
OP 已上线，等缓存更新后，可以观察数据。
