### ISSUE TITLE
预取环境 mip1 和 mip2 同时执行可能导致冲突

### ISSUE THREAD

**Issue by yenshih** [mipengine/mip2#414]
**BUG 描述**
 - 预取环境 mip1 和 mip2 同时执行导致冲突，可能的原因为先后写入 `MIP` 变量，`customElement.define` 了同名组件等
 - mip2 入口文件 `index.js` 仅对多次执行 mip2 有过滤，并未考虑预取环境或与 mip1 同时存在的情况
 - mip1 则完全没有对执行做限制
 - mip1 带有 `esl`，而mip2 构建类型为 `umd`，此时双方先后加载，mip2 将会调用空的 `define` 分支，错误地掩盖了此问题

**复现步骤**
 - mip2 构建类型改为 `iife`
 - 预取环境报错

**期望结果**
 - mip1 与 mip2 同时存在时无冲突，应在双方入口文件处做更严格限制
 - 预取环境时 mip1 与 mip2 都不应执行

**Comment by PengXing** [comment]
这个需求如果需要更改 MIP1 的代码，可以去改

**Comment by yenshih** [comment]
后续不再维护 MIP1，这个 issue 可以关了。
