### ISSUE TITLE
mip1Polyfill 使用 window.customElements.define 注册自定义组件

### ISSUE THREAD

**Issue by zoumiaojiang** [mipengine/mip2#415]
**要解决什么问题**

> `document.registerElement` is deprecated and will be removed in M73, around March 2019. Please use `window.customElements.define` instead. 

**描述一下你理想中的解决方案**

使用 Custom Element v1 API 替代 mip1 的 Custom Element v0 API

**Comment by yenshih** [comment]
@huanghuiquan 这个看起来比较紧急，但是搞了下发现 v0 没有 `observedAttributes`……
这应该是 breaking change，如何是好

**Comment by huanghuiquan** [comment]
@yenshih 这个需要

**Comment by huanghuiquan** [comment]
> @huanghuiquan 这个看起来比较紧急，但是搞了下发现 v0 没有 `observedAttributes`……
> 这应该是 breaking change，如何是好

这个貌似无解，先统计下 mip1 站长组件里有多少组件使用了 attributeChangedCallback 这个接口吧
