### ISSUE TITLE
MIP 页面的 URL 带中文字符是否满足 MIP 规范

### ISSUE THREAD

**Issue by clark-t** [mipengine/mip2#434]
目前有部分站长反映，在使用 https://www.mipengine.org/validator/preview 进行 MIP 页在线校验的时候，对于 URL 中带有中文字符的网站会提示抓取不到页面，从而导致校验失败。同样的这个问题也会导致资源平台的校验失败。
虽然可以引导站长对中文字符做编码处理，但在这里想问对于这种带有中文字符的 URL 是否满足 MIP 规范呢？如果满足的话，我们需要对 validator 做处理。

**Comment by PengXing** [comment]
MIP 的规范只是对于 MIP 页面的规范，MIP 页面的 URL 中存在中文不应该是 MIP 规范的事情，而应该修改 validator 页面提示 URL 不合法

**Comment by Ricardo-Li** [comment]
我来跟进校验&站长平台，增加一个非法提示。

**Comment by Ricardo-Li** [comment]
在官网的校验工具抓取网页不存在时，增加了一个检查 URL 是否合法的提示，暂时先这样观察后续有无站长反馈。

另在线下测试时 node > 9 环境中，此处可直接 catch 到报错为 `ERR_UNESCAPED_CHARACTERS`。但是官网 bce 环境 node 版本为 v4.4.2，抓取网页 404。
