### ISSUE TITLE
mip-shell 翻页切换时闪动

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip2#44]
背景：小说夜间模式切换时，页面会闪白。
### 问题2：头部切换时样式反白一下，且宽度不沾满屏幕
![loading](https://user-images.githubusercontent.com/8498677/42572803-f3b514c2-854c-11e8-8e49-87f0192d8d57.gif)

**Comment by easonyq** [comment]
问题1应该是我们这边的问题，我会尽快修复；
问题2是因为头部需要单独的fade动画，因此创造了一个新的 div class='mip-page-fade-header-wrapper'。你在变成夜间模式的时候，应该一并把这个DOM也变成黑色，就OK啦~

**Comment by easonyq** [comment]
问题1也修复了
