### ISSUE TITLE
mip-stat-baidu v2 组件统计不正常

### ISSUE THREAD

**Issue by clark-t** [mipengine/mip2#458]
**BUG 描述**
站长反馈 v2 的 mip-stat-baidu 百度统计不正常，但是换回 v1 的 mip-stat-baidu 统计就好了，需要比对下这两个版本组件的实现逻辑是否正常。

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by zoumiaojiang** [comment]
这个 bug 提到 mip2-extensions 里面去吧。
