### ISSUE TITLE
mip-shell 默默地return false然后不展示了，希望在控制台增加报错提示

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip2#46]
![image](https://user-images.githubusercontent.com/8498677/42615698-f4214c14-85dd-11e8-8cb7-4acff2541803.png)

pattern要求跟页面名称对应，但如果站长pattern写的是`xiaoshuo-\\d`，实际页面是`name-123`就会对应不上，控制台也没有报错，一脸懵逼~

可以加个console.error提示下~

**Comment by easonyq** [comment]
在匹配不到任何规则的时候，现在会弹出一句提示：
`console.warn('Cannot find MIP Shell Config for current page. Use default instead.')`
