### ISSUE TITLE
on:tap 事件在 windows Chrome PC 网页模式下无法触发

### ISSUE THREAD

**Issue by clark-t** [mipengine/mip2#460]
**BUG 描述**
在 windows Chrome PC 网页模式下无法触发 on:tap 事件，但是打开手机模拟器模式的话可以触发。

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by yenshih** [comment]
```js
`ontouchstart` in window
```
在 Chrome 68 下为 `true`，升级到 Chrome 71 后为 `false`，应该是修复了

问题又变成了触屏的 windows 电脑应该怎么办
