### ISSUE TITLE
反馈:docs/components/dynamic-content/mip-script.md

### ISSUE THREAD

**Issue by jiebin1996** [mipengine/mip2#461]
TypeError: MIP.sandbox.strict.document.getElementById is not a function[详细了解] m.lysou.cn:1:14

    <anonymous> http://m.lysou.cn/:1 d https://c.mipcdn.com/static/v2/mip-script/mip-script.js:1 D https://c.mipcdn.com/static/v2/mip-script/mip-script.js:1 connectedCallback https://c.mipcdn.com/static/v2/mip-script/mip-script.js:1 i https://c.mipcdn.com/static/v2/mip.js:1 value https://c.mipcdn.com/static/v2/mip.js:1 value https://c.mipcdn.com/static/v2/mip.js:1 ur https://c.mipcdn.com/static/v2/mip.js:1 customElement https://c.mipcdn.com/static/v2/mip.js:1 yc https://c.mipcdn.com/static/v2/mip.js:1 value https://c.mipcdn.com/static/v2/mip.js:1 value self-hosted:976 func https://c.mipcdn.com/static/v2/mip-script/mip-script.js:1 value https://c.mipcdn.com/static/v2/mip.js:1 value https://c.mipcdn.com/static/v2/mip.js:1 value self-hosted:974 <anonymous> https://c.mipcdn.com/static/v2/mip-script/mip-script.js:1 

使用script组件显示方法不存在

**Comment by yenshih** [comment]
https://www.mipengine.org/v2/docs/interactive-mip/custom-js-by-using-mip-script.html
