### ISSUE TITLE
on 语法支持 MIP.scrollTo MIP.navigateTo 等方法调用

### ISSUE THREAD

**Issue by clark-t** [mipengine/mip2#467]
**要解决什么问题**
目前 on 语法只能触发组件事件和修改数据（setData），但对于比较常用的 url 跳转、页面锚点滚动等功能并没有提供相应的方法，导致不得不通过比较复杂的 mip-bind + mip-data + mip-script 相互配合去实现，一般站长则会选择写个性化组件去实现，这些都是不太可取的，因此希望能够跟 AMP 对齐。

**描述一下你理想中的解决方案**
可参考 AMP 的实现方案：https://www.ampproject.org/docs/interaction_dynamic/amp-actions-and-events#special-targets

**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

**Comment by zoumiaojiang** [comment]
和 #600  关联
