### ISSUE TITLE
反馈:docs/components/layout/mip-fixed.md

### ISSUE THREAD

**Issue by gitcwx** [mipengine/mip2#469]
MIP v2 版本 mip-gototop无效；
引入v1版本的mip-fixed组件也无效 https://c.mipcdn.com/static/v1/mip-fixed/mip-fixed.js；
需要引入  https://mipcache.bdstatic.com/static/v1/mip-gototop/mip-gototop.js

**Comment by huanghuiquan** [comment]
@gitcwx https://www.mipengine.org/v2/components/dynamic-content/mip-gototop-case-0.html 我看这个是有效，能具体描述下问题问题吗？

**Comment by gitcwx** [comment]
我通过mip-fixed组件找到的 mip-gototop 案例，这个是无效的
https://www.mipengine.org/v2/components/layout/mip-fixed-case-6.html
后来我发现 v2版本的 mip-gototop 也是有单独组件的，引用v2版本的是可以的，是我的问题，抱歉！

**Comment by gitcwx** [comment]
> @gitcwx https://www.mipengine.org/v2/components/dynamic-content/mip-gototop-case-0.html 我看这个是有效，能具体描述下问题问题吗？
我通过mip-fixed组件找到的 mip-gototop 案例，这个是无效的
https://www.mipengine.org/v2/components/layout/mip-fixed-case-6.html
后来我发现 v2版本的 mip-gototop 也是有单独组件的，引用v2版本的是可以的，是我的问题，抱歉！
