### ISSUE TITLE
切换页面时会出现在白屏闪动现象

### ISSUE THREAD

**Issue by zhuguoxi** [mipengine/mip2#47]
**复现步骤**
在视频第4秒出切换出现白屏

**期望结果**
不出现在最好

**截图**
没截图，有视频
[闪屏.mp4.zip](https://github.com/mipengine/mip2/files/2188360/mp4.zip)

**环境及版本信息:**
 - OS: ios
 - UC/手百
 - mip-cli Version

**Comment by zhuguoxi** [comment]
这个不是单个浏览器问题哈，有很多机型以及浏览器出现在这种问题  @xiaoiver @PengXing @easonyq 麻烦优化这一块

**Comment by xiaoiver** [comment]
![image](https://user-images.githubusercontent.com/3608471/42919673-98de39bc-8b45-11e8-8d36-e86009b2f81d.png)
