### ISSUE TITLE
怎么实现复制，粘贴功能

### ISSUE THREAD

**Issue by christy-zoey** [mipengine/mip2#470]
**要解决什么问题**
用js原生方法实现复制粘贴时
document.execCommand("Copy")
会报错：
MIP.sandbox.document.execCommand is not a function

**描述一下你理想中的解决方案**
可以加入复制，粘贴的组件，

**描述你的备选方案**
 给mip的方法里面加入execCommand

**Comment by clark-t** [comment]
需要对 CLI 工具做下升级，下一个版本支持

**Comment by yenshih** [comment]
@clark-t 应该暂时只放开 `execCommand` 的 `cut` `copy` `paste` 功能吧，我感觉这个函数略危险

**Comment by clark-t** [comment]
已上线
