### ISSUE TITLE
mip-mustache 需要申请 Mustache.js 的 npm 包

### ISSUE THREAD

**Issue by craigchencc** [mipengine/mip2#483]
**要申请的 npm 包名**
多个 npm 包名需要换行
mustache

**描述一下添加该 npm 包的必要性**
清晰准确的描述为什么需要这个 npm 包
mip-mustache 需要申请 Mustache.js 的 npm 包

**补充信息**
补充其他信息，如截图等

**Comment by clark-t** [comment]
done
