### ISSUE TITLE
之前检测通过的mip页面，开始报错

### ISSUE THREAD

**Issue by hanjiuzhou199911** [mipengine/mip2#487]
**BUG 描述**
之前检测通过的mip页面，现在全部报检测错误，这种情况之前出现过一次，那次后来自己好了
网址：m.zikaowang.org
**复现步骤**
重新复现 Bug 的步骤
1.发现mip页面效验哪里返回好多效验错误
2.用mip页面检测工具测试页面，发现不止文章页面，连首页、之前检测通过的所有页面都检测报错。
**期望结果**
想知道是自己的原因还是那些地方冲突了，而且这个事情之前也出现过。突然之间mip页面全部检测失败，页面上明明有的，但是检错却报错

**截图**
![405tp_ uc 7v r0g8tt 9 o](https://user-images.githubusercontent.com/33077830/51440778-72d34080-1d05-11e9-8b26-26d7c9e64ce7.png)
![2l7a8vznw0otbxui9 erp r](https://user-images.githubusercontent.com/33077830/51440793-9dbd9480-1d05-11e9-83fe-57a6a31cabec.png)
![wq7 q m x1b6 xi 2](https://user-images.githubusercontent.com/33077830/51440842-1f152700-1d06-11e9-8eda-575ced45fa0e.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli

**其他信息**
都是用的支持的组件，没有自己的开发组件。现在是用的事v1版本，因为说组件没有更新完所以没有用v2

**Comment by yenshih** [comment]
验证源代码而不是运行时代码

**Comment by hanjiuzhou199911** [comment]
现在又可以了，昨天预览页面打开报错，所以我把网页上代码复制到哪里，报了好多错误。今天上午看mip预览页面可以打开了，测试网址。现在又可以了
