### ISSUE TITLE
mip2 支持vuex 的组件状态管理工具吗？

### ISSUE THREAD

**Issue by shao-kang** [mipengine/mip2#49]
![1](https://user-images.githubusercontent.com/15928370/42633618-a79fa328-8613-11e8-8666-d0f9886db87f.png)

因为要做一个比较复杂的im 组件，需要状态管理，mip2 支持vuex  的状态管理工具吗？有计划支持吗？

**Comment by huanghuiquan** [comment]
mip 本身不适合做这么复杂交互的页面和组件，mip2 暂时不支持 vuex 的状态管理工具，还没有计划支持
