### ISSUE TITLE
反馈:docs/components/dynamic-content/mip-mustache.md

### ISSUE THREAD

**Issue by shao-kang** [mipengine/mip2#494]
没有具体文档差评，

**Comment by PengXing** [comment]
`mip-mustache` 在 v1 版本是没有文档的，前人的锅，后人来填，所以在我们迁移 v1 到 v2 的时候都补充了完整的文档，可以看这里，https://github.com/mipengine/mip2-extensions/blob/dev-sync/components/mip-mustache/README.md QA 正在测试中，预计明天上线，同时文档也会更新

**Comment by shao-kang** [comment]
谢谢大佬
