### ISSUE TITLE
mip-env组件去掉cache相关描述信息

### ISSUE THREAD

**Issue by html5david** [mipengine/mip2#497]
**要解决什么问题**
清晰准确的描述要解决什么问题
mip-env组件中scope参数中cache与dp处理是相同的，但多数站长无法理解cache含义，在使用上有很大歧义，建议删除对cache的说明，之后cache有了单独作用时再加上
**描述一下你理想中的解决方案**
清晰准确的描述你想怎么解决
mip-env组件去掉cache相关描述信息
**描述你的备选方案**
清晰准确的描述你考虑的备选方案
mip-env组件去掉cache相关描述信息
**补充信息**
补充其他信息，如截图等

**Comment by huanghuiquan** [comment]
mipengine/mip2-extensions/pull/487
