### ISSUE TITLE
核心组件mip-img新增浏览体验需求

### ISSUE THREAD

**Issue by VenyXiong** [mipengine/mip2#50]
需求描述：
mip-img 中存在一个popup属性，可以控制点击图片采用弹出的形式浏览大图。但是这种浏览能够实现单张浏览。现在希望在这个基础上，能够扩展这个功能，点击图片弹出大图浏览时，可以进行左右滑动切换，浏览页面上其他配置了popup属性的图片。
一个具体的yi应用case如下图所示：
https://mip.putibaby.com/master_card?mcode=x6f3adb702b5c7a530aee9f6a3e4bf78f

![image](https://user-images.githubusercontent.com/3196280/42670751-51c24bd2-868f-11e8-8200-da5d7306e07a.png)
![image](https://user-images.githubusercontent.com/3196280/42670775-7d527cea-868f-11e8-9931-452fec233014.png)

**Comment by PengXing** [comment]
这个需求后续可以支持，现在我还不能给确定的时间

**Comment by VenyXiong** [comment]
这部分如果暂时无法给出支持预期的话，我们尽量保证功能升级对合作方的透明吧，后续我们升级完成之后他们直接可用~
