### ISSUE TITLE
mip-video在安卓uc和qq浏览器下，播放后，播放器会覆盖层级更高的元素

### ISSUE THREAD

**Issue by mrqway** [mipengine/mip2#503]
**BUG 描述**
清晰和准确的描述 Bug 是什么
mip-video在安卓uc、qq浏览器上，覆盖在播放器上面的元素（设置了z-index），一旦点击播放，之前覆盖在播放器上面的元素就会被播放器覆盖了，暂停播放时，仍然会被播放器覆盖。

**复现步骤**
重新复现 Bug 的步骤
 1.简单的demo，mip-video上覆盖层级更改的元素，播放时，元素会被覆盖。

**期望结果**
兼容各个浏览器下，播放后，元素的层级不会变更

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
安卓系统，uc浏览器和qq浏览器

**其他信息**
其他补充信息

**Comment by huanghuiquan** [comment]
麻烦提供下示例代码，谢谢

**Comment by huanghuiquan** [comment]
我按照你的描述试了下使用原生 video 标签，也是会被覆盖，猜测是 uc 和 qq 浏览器对视频做了特殊处理，和 mip-video 没有关系

```html
  <video poster="https://www.mipengine.org/static/img/sample_04.jpg"
    controls="" 
    width="640" 
    height="360" 
    src="https://gss0.bdstatic.com/-b1Caiqa0d9Bmcmop9aC2jh9h2w8e4_h7sED0YQ_t9iCPK/mda-gjkt21pkrsd8ae5y/mda-gjkt21pkrsd8ae5y.mp4">
  </video>
  <div class="mask"></div>
```
