### ISSUE TITLE
m-bind数据绑定后工具验证说不符合规范

### ISSUE THREAD

**Issue by zcdnsz** [mipengine/mip2#504]
**BUG 描述**
用m-bind绑定数据后,到官网的验证工具里面验证说不符合MIP规范.....

**复现步骤**
重新复现 Bug 的步骤
1. 设置数据源

<mip-data>
  <script type="application/json">
   {
      "url": 'https://www.baidu.com',     
    }
  </script>
</mip-data>

2. 绑定数据

`<a  m-bind:href="url">namename</a>`

3. mip官网验证工具说不符合规范
![mip](https://user-images.githubusercontent.com/46695625/51952986-7c7f4580-2475-11e9-8681-24347935b517.png)
[https://user-images.githubusercontent.com/46695625/51952986-7c7f4580-2475-11e9-8681-24347935b517.png](url)

**Comment by iamzhaobo** [comment]
JSON不符合规范，注意使用双引号

**Comment by yenshih** [comment]
我们暂时不支持使用`m-bind:href`，如果确实有需要可以先写一个 `href` 绕过
https://www.mipengine.org/v2/docs/mip-standard/mip-html-spec.html
