### ISSUE TITLE
MIP连接到非MIP页用相对路径在CDN上会报错还是回源?

### ISSUE THREAD

**Issue by zcdnsz** [mipengine/mip2#505]
由于mip会自动把网页缓存到CDN上,2个网页之间A连接,一个是MIP一个非MIP,用相对路径是否会发生错误?

如:
A是mip B非MIP
A连接B用的是相对路径连接,由于A是mip会被自动缓存到CDN上,由于B不是MIP网页不会被缓存到CDN上,那么,当用户由A网页跳转到B网页的时候,撒会报错还是会回源呢?

**Comment by huanghuiquan** [comment]
cdn 抓取后会补全相对路径为绝对路径，所以会正确地跳转到源站
