### ISSUE TITLE
添加 ga 到 sanbox 白名单

### ISSUE THREAD

**Issue by halfer53** [mipengine/mip2#508]
**要解决什么问题**
我写了一个 Google Analytics 的组件， 用于Google Analytics 统计。由于 windows.ga 属于全局变量，而且此组件具备通用性，因此需要将 windows.ga 添加到 sandbox 白名单

PR 详见： https://github.com/mipengine/mip2-extensions-platform/pull/517
文档：https://developers.google.com/analytics/devguides/collection/analyticsjs/

**描述一下你理想中的解决方案**
添加 ga 到白名单

**描述你的备选方案**
用MIP1 的 组件，但是有很多局限

**补充信息**

**Comment by yenshih** [comment]
这个组件比较通用，可以给官方组件提 PR，麻烦到这里提一下 https://github.com/mipengine/mip2-extensions
谢谢

**Comment by yenshih** [comment]
@halfer53 官方组件没有沙盒限制，不需要添加白名单，这个也先 close 了

**Comment by halfer53** [comment]
不好意思回复晚了，这几天一直在加班。https://github.com/mipengine/mip2-extensions/pull/525
