### ISSUE TITLE
申请添加白名单

### ISSUE THREAD

**Issue by eat-full** [mipengine/mip2#511]
**要解决什么问题**
项目中需要用到较多动画，使用到第三方动画库 velocity

**描述一下你理想中的解决方案**
希望能将该库加入白名单

**描述你的备选方案**
是否有可能的动画库推荐

**补充信息**
该工具为vue官方推荐库，链接：https://github.com/julianshapiro/velocity

**Comment by clark-t** [comment]
优先考虑使用 MIP 自带动画解决方案 naboo：https://www.mipengine.org/v2/api/util/naboo.html，如不满足开发需求，请详细说明
