### ISSUE TITLE
【项目-async 实验推进】小说翻几页后出现报错cannot read property “appendchild” of null

### ISSUE THREAD

**Issue by gaoshan003** [mipengine/mip2#516]
**BUG 描述**
https://psfehttps3.baidu.com:8443/s?word=延禧攻略
小说翻几页后出现报错cannot read property “appendchild” of null
![image](https://user-images.githubusercontent.com/39788046/53391306-ed604180-39d0-11e9-9469-a9554c99bcea.png)

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by zoumiaojiang** [comment]
这是一个 iOS + iframe 环境下才会触发的 bug，初步排查原因是因为 async 加载 mip.js 之后，一开始执行viewport 模块引入的 rect 模块中的全局定义的 document.body 没有 ready，导致报错。
