### ISSUE TITLE
申请添加现代化的“复制到剪切板”插件-clipboard

### ISSUE THREAD

**Issue by eat-full** [mipengine/mip2#520]
**要申请的 npm 包名**
clipboard

**描述一下添加该 npm 包的必要性**
用户需求点击点击复制到剪切板功能

**补充信息**
包地址：https://clipboardjs.com/

**Comment by jenkey2011** [comment]
mip v1组件给小说写过一个，复制组件，使用简单
https://github.com/mipengine/mip-extensions-platform/tree/master/mip-xiaoshuo-clipboard

**Comment by eat-full** [comment]
收到，谢谢
