### ISSUE TITLE
【项目-async 实验推进】小说页面翻页中有页面头部空白过多

### ISSUE THREAD

**Issue by gaoshan003** [mipengine/mip2#525]
**BUG 描述**
小说页面翻页中有页面头部空白过多
https://psfehttps3.baidu.com:8443/wishwing/c/s/wenxue.m.iqiyi.com/act/nocache/mipReader-18l2h9t25p-18l2zsz5rb.html%3Fbaiduvs%3D222623839%26page%3D1?novel=1&word=&title=&lid=7807845383624309869&referlid=7807845383624309869&ms=1&frsrcid=5064&frorder=2
![image](https://user-images.githubusercontent.com/39788046/53628224-6bc51980-3c45-11e9-92c9-89a3190b6820.png)

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by yenshih** [comment]
由于 async，mip 核心插入组件样式时，mip.css 的 DOM 可能还未生成，需要改成
```js
var mipCssLink

function createStyleElement () {
  var styleElement = document.createElement('style');
  styleElement.type = 'text/css';
  if (!mipCssLink) {
    mipCssLink = head.querySelector('link[rel=stylesheet][href*="/mip.css"]')
  }
  head.insertBefore(styleElement, mipCssLink && mipCssLink.nextSibling || head.firstChild);
  return styleElement
}
```
@clark-t mip-components-webpack-helper 也需要同步
