### ISSUE TITLE
【项目-async 实验推进】video点击播放按钮无法播放，且有报错

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2#528]
**BUG 描述**
【项目-async 实验推进】video点击播放按钮无法播放，且有报错
测试地址：https://psfehttps3.baidu.com:8443/mip/c/s/m.120ask.com/voice/mip_39812.html

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图
![image](https://user-images.githubusercontent.com/46017563/53636519-7a1e3000-3c5b-11e9-9069-251ee48650d9.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by yenshih** [comment]
测试环境跨域问题，与 async 无关
