### ISSUE TITLE
mip-shell 自定义颜色后，切换页面，背景变化不一致

### ISSUE THREAD

**Issue by zhuguoxi** [mipengine/mip2#53]
**BUG 描述**
mip-shell 自定义颜色后，切换页面，背景变化不一致； 以及切换时，头部颜色切换需要有过渡

**截图**
![截图](https://user-images.githubusercontent.com/7043799/42792140-917ee9f0-89a6-11e8-9c26-20a6fdf33782.gif)

**Comment by easonyq** [comment]
你需要覆盖掉 `<div class="mip-page-fade-header-wrapper">` 的样式，和头部一致即可。
