### ISSUE TITLE
反馈:docs/components/layout/mip-sidebar.md

### ISSUE THREAD

**Issue by linchunda** [mipengine/mip2#531]
我用这个组件制作侧边栏菜单，但菜单长度较少时，显示宽度太小，好难看，能设置最小的宽度吗？

**Comment by PengXing** [comment]
你可以自定义 `mip-sidebar` 的 css，如下

```html
<style mip-custom>
mip-sidebar {
  max-width: 50%;
}
</style>
```

**Comment by linchunda** [comment]
多谢，根据您的提示已经解决
由于你们的css默认 min-width:45px!important;我修改为min-width: 150px!important;

	<style mip-custom>
	  mip-sidebar{min-width: 150px!important;padding: 15px;}
    </style>

建议你们的css最小修改为100px;
