### ISSUE TITLE
mip-bind 绑定的属性为class 时，dom解析不正确

### ISSUE THREAD

**Issue by VenyXiong** [mipengine/mip2#54]
**BUG 描述**
mip-bind 绑定的属性为class 时，dom节点渲染不正确
![image](https://user-images.githubusercontent.com/3196280/42802659-22dfd678-89d6-11e8-9588-4501491038d6.png)
![image](https://user-images.githubusercontent.com/3196280/42802662-2507818a-89d6-11e8-850c-e8b408e41c1f.png)

**Comment by ccksfh** [comment]
fixed
