### ISSUE TITLE
【MIP 核心升级 Babel 版本至 v7】IOS8（iPhone 5s）妈妈网 图片一直不显示

### ISSUE THREAD

**Issue by cjgjy1126** [mipengine/mip2#550]
**BUG 描述**
【MIP 核心升级 Babel 版本至 v7】IOS8（iPhone 5s）妈妈网 图片一直不显示
链接：http://cp01-sys-rpm14.cp01.baidu.com:8003/mip/c/m.mama.cn/bk/mip/art/46840/?s_j=1

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
![image](https://user-images.githubusercontent.com/46017563/54595665-0d35d300-4a6e-11e9-95f8-bd6e88893fe3.png)

**环境及版本信息:**
 IOS 8

**其他信息**
其他补充信息

**Comment by clark-t** [comment]
solved
