### ISSUE TITLE
开发第三方组件过程中，let MIP = window.MIP || {} 编译出错 

### ISSUE THREAD

**Issue by craigchencc** [mipengine/mip2#554]
**BUG 描述**
清晰和准确的描述 Bug 是什么

开发第三方组件过程中，let MIP = window.MIP || {} 编译出错 

编译成了 var t = t.sandbox.window.MIP || {}

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by clark-t** [comment]
done
