### ISSUE TITLE
mip-showmore 显示更多 组件 BUG

### ISSUE THREAD

**Issue by gom3250** [mipengine/mip2#557]
**BUG 描述**
当需要收起内容，图片比较多的情况，没有计算图片高度，导致没有收起。

**复现步骤**
文字比较少，图片比较多的时候

**期望结果**
希望可以计算下图片的高度。

**截图**
http://m.qqtn.com/mipc/240324.html
问题页面地址

**环境及版本信息:**
 - OS: 安卓，ios
 - Browser 所有浏览器
 - mip-cli 版本   V1  V2 都试过

**Comment by PengXing** [comment]
我自己演示了一下，没发现有什么问题，能详细的指出问题在哪里吗？

**Comment by gom3250** [comment]
比如我设置了。高度为500.但是正好文本比较少，图片比较多的情况。没有计算图片的高度，导致认为内容高度不足500.。
