### ISSUE TITLE
官方组件和第三方组件编写规范

### ISSUE THREAD

**Issue by PengXing** [mipengine/mip2#57]
越来越多的官方组件和第三方组件提交，为了可维护性和代码统一，因此需要对组件提出一些规范的要求，需要遵守的规范包括：

- 目录规范
- 文档规范
- 代码规范
- 命名规范

**Comment by chenqiushi** [comment]
## 目录规范

### 1. 官方组件

对于[官方组件仓库](https://github.com/mipengine/mip2-extensions)，开发者主要只需关心 `components`、`common`、`static` 三个目录下的内容，其中：

- [MUST] 所有组件必须在 `components` 目录下编写
- [MUST] `components` 目录下的组件目录必须以 `mip-xxx` 的形式命名
- [MUST] `components/mip-xxx` 组件目录下，必须包含 ① `example` 示例，② vue 组件 `mip-xxx.vue`，③ 组件说明文件 `README.md` 
- [MUST] `components/example` 目录至少包含一个使用了该组件的示例 html
- [SHOULD] `common` 目录用于放置公用的工具类方法如 utils.js 等 ，组件中 import 使用即可
- [SHOULD] `static` 目录用于放置图片、字体文件

### 2. 第三方（站长）组件

[第三方组件仓库](https://github.com/mipengine/mip2-extensions-platform#mip2-extensions-platform)以项目（一个站点）的粒度来管理站长组件。所有的站长组件位于 `sites` 目录

- [MUST] 站长组件必须提交到 `sites` 目录，且以站点的名称命名，如 `xiongzhang.baidu.com`
- 站长组件目录结构与官方组件基本一致，规范参考上述第 1 点。


欢迎补充。

**Comment by PengXing** [comment]
## 文档规范

文档规范指的是各组件目录下的 README.md 文件的编写规范，MIP2 复用 MIP1 的规范

参考 https://github.com/mipengine/mip-extensions/blob/master/docs/spec-readme-md.md

**Comment by liuruoran88** [comment]
# 代码规范

## MIP HTML 规范

MIP规范是高性能 MIP页面的保证，其中最重要的规范是：MIP HTML规范。按照页面功能区域划分，MIP HTML规范主要分为以下列出的若干类型。
- 头部规范；
- 页面元素和属性规范；
- 自定义样式规范。
由于规范长期更新，更多最新规范可查阅MIP官方网站 MIP HTML规范章节。

### 1．头部规范
下面简要列出MIP页头部的使用规范。头部是MIP页的声明、配置信息、资源引入的主要区域。
  - 起始标签使用<!DOCTYPE html>：HTML5页面的唯一头部声明，告知浏览器当前 HTML页面的版本。
  - HTML标签必须加上 MIP标记，即<html mip>：告知搜索引擎此页面是MIP页面。
  - 必须包含<head>和<body>标签：HTML5的标准约定，通过这两个标签进行功能区块划分。
  - 必须在head标签中包含字符集声明: meta charset="utf-8"，字符集统一为utf-8。
  - 必须在head标签中包含 viewport 设置标签: <meta name="viewport" content="width=device-width,initial-scale=1">，推荐包含minimum-scale=1。
  - 必须在head标签中包含<link rel="stylesheet" type="text/css" href="https:// c.mipcdn.com/static/v1/mip.css" >：MIP 框架的主样式表，引入保证页面正常工作。
简单来说，MIP页头部规范包含这几种类型：① HTML5标准规范，HTML5标准规范是MIP页规范的基础，如对<!DOCTYPE html>的强制要求；② 对头部标签的属性限制和扩展，限制一些标签的属性来配合MIP 共同完成页面预期功能，如<meta charset="utf-8">；③ 引入MIP 资源，一般是引入有必要前置的样式表和脚本，同时也可以自定义插入样式。

### 2．页面元素和属性规范
MIP HTML规范对页面的元素和属性进行了约束和限制，目的是最大程度地提升页面性能、保证页面安全、提高开发效率。
对于页面元素来说，MIP HTML规范中主要做了以下几个限制。

（1）强制引用MIP 依赖脚本
必须在body标签中包含<script async src="https://c.mipcdn.com/static/v2/mip.js" </script>，建议使用最新版本的 mip.js 并且放在body的底部。这样做的目的是：引入MIP 主脚本，获得 MIP 最新核心功能；设置为async和放置于body底部，保证脚本的加载不会阻塞页面的加载和渲染，使页面第一时间展示给用户（如果有兴趣，读者可以查阅本书性能优化第六章的内容，也可以查阅首屏优化相关资料）。
（2）禁止使用对页面性能以及安全有较大影响的标签，请将其替换为MIP的特有标签
对于标签的限制是MIP HTML规范的重要部分，对若干性能差、安全性弱、开发不友好的标签限制使用，替换为MIP 提供的组件标签。这样很好地规避了问题，同时，使用MIP 精心设计的组件和其他站点贡献的组件，可以大大减小 MIP页面的开发量。以<img>为例，MIP 强制标签替换为<mip-img>，并且按照组件的使用方式调用。这样 MIP 框架可以对页面的所有图片进行统一管理和优化，如懒加载、webp等。

（3）为了搜索引擎抓取和收录，优化使用特定标签和属性
MIP页面本身具有良好的性能表现，结合搜索引擎和静态cache，性能优势能发挥到极致。对于搜索引擎的优化，主要靠标签的属性设置来告知搜索引擎 MIP页面的相关信息。如强制在head标签中包含 <link rel="canonical" href="https://xxx">，保证搜索引擎知晓 MIP页和HTML5页面的对应关系。

对于页面元素的属性来说，MIP HTML规范主要做了以下两个限制。
① 遵守 HTML5标准规范。
② 禁用事件相关属性on(xxx)。
例如，on、onclick、onmouseover等不能在MIP页使用。MIP 框架会代理主要的页面事件。对于一些影响性能和开发效率的属性，MIP 框架进行了优化，保证对整个页面事件的统一、安全地管理。

（4）MIP HTML中不允许使用style属性
内联 style 影响页面的渲染性能，MIP页中不允许在页面标签上使用style属性，所有的样式必须放置在头部 style标签中统一管理。

### 3．自定义样式规范
如前面所述：出于性能考虑，HTML中不允许使用内联 style，所有样式只能放到head的style标签里。样式在内容渲染前加载，可以减少重绘和回流（感兴趣的读者可以查阅重绘和回流相关资料），大大提升渲染性能。
以下案例从正反两方面说明 style的规范。

正确方式：
```js
<head>
    <style mip-custom>
        p { color: #00f;}
    </style>
</head>
<body>
    <p>Hello World!</p>
</body>
```

错误方式：

```html
<p style="color:#00f;">Hello World!</p>
<p>
    <style>
       p { color: #00f;}
    </style>
</p>
```




## JS代码规范

### 具体规范
- MIP 项目中 JS 代码统一都遵循 JavaScript Standard Style 规范，且必须通过 ESLint 工具审核之后才能提交，一般不允许使用 eslint-disable 来豁免检测。
- 所有样式文件必须使用UTF-8编码。
- 组件的脚本开发采用ES6和ES Module的编写方式。
- Vue 文件的 template 部分需要遵守 Vue 的编码规范。

尤其是在多方合作的项目开发中，遵守统一的 JS 代码规范，显得尤为重要。

### 2.检验工具

MIP初始化项目中，已经为开发者配置好了 ESLint 校验工具，开发者可以通过简单命令行完成代码的检验及校正工作。项目中 "eslint-config-standard" 作为 ESLint 的规范配置引入, 在  `.eslintrc.json` 的 "extends" 配置项中使用，不需要额外安装 standard 工具，编辑器也不需要安装 standard 插件，只需要安装 ESLint 的代码检查插件即可。
具体的命令行可以参考 `package.json`  文件中 scripts 的配置。

### 2.编辑器校正工具

除此之外，开发者也可以在编辑器中做相应的设置或引入特定的插件，让编辑器去完成部分校正工作，这里列出了部分编辑器及插件供开发者参考：

### (1) Sublime Text
通过 Package Control，安装 SublimeLinter 和 SublimeLinter-contrib-standard。如果想要保存时自动格式化，还需安装StandardFormat。
### (2) Atom
安装linter-js-standard。如果想要保存时自动格式化，还需安装standard-formatter。
安装standardjs-snippets 可以获得snippets特性。
### (3) Visual Studio Code
安装vscode-standardjs（已经包含了自动格式化）。
安装vscode-standardjs-snippets 以获得JS snippets安装vscode-react-standard以获得React snippets。


## 组件样式开发规范

- 组件的样式开发必须遵循 Stylelint 中 stylelint-config-standard 中的规范，且必须通过 Stylelint 工具审核之后才能提交。
- 所有样式文件必须使用UTF-8编码 UTF-8 编码具有更广泛的适应性，避免不必要的麻烦，请使用此编码。
- 不允许使用ID选择器：组件的设计，需要考虑一个页面上同时存在多个组件的场景。所以组件及内部元素都不应该拥有hard code的ID属性。
- 选择器的第一层如果是标签选择器，只允许使用组件自身标签，组件的样式定义应只对组件本身以及组件内部生效。

```css
/* good */
mip-sample span {
    color: red;
}

/* bad */
span {
    color: red;
}
```

- class选择器的命名必须为组件名，或以组件名为前缀。
组件的样式定义应尽量避免对使用方页面产生影响。短小简捷的class 容易与使用方页面产生冲突。

```css
/* good */
.mip-sample-title {
    color: red;
}

/* bad */
.title {
    color: red;
}
```

**Comment by PengXing** [comment]
## 命名规范

命名规范涵盖一下几个部分
- 组件命名规范
- 组件属性命名规范
- 组件配置命名规范


### 组件命名规范

MIP 扩展组件仓库 下，每个 mip- 前缀的目录为一个扩展组件。其中：
- 目录名称为组件名称
- 目录名称（组件名称）必须是 mip- 为前缀的全小写字符串，以 `-` 分隔

### 组件属性命名规范

自定义属性[强制]单词全字母小写，单词间以 - 分隔

```html
<mip-a some-attribute="xxx"></mip-a>
```

### 组件配置命名规范

MIP 自定义组件的配置项需符合 Camel 规范，不得采用中划线

```html
<mip-a>
  <script type="application/json">
  {
      "goodAttribute": "good",
      "bad-attribute": "bad"
  }
  </script>
</mip-a>
```

**Comment by jenkey2011** [comment]
```html
<mip-a>
  <script type="application/json">
  {
      "goodAttribute": "good",
      "bad-attribute": "bad"
  }
  </script>
</mip-a>
```
1、属性可以写在本地json，也可以写在属性里
2、标签属性的规范是连字符形式

那么`bad-attribute`是不是更好、更兼容呢？

**Comment by PengXing** [comment]
@jenkey2011 

只有 HTML 和 CSS 里才是中划线命名，而写在 `<script type="application/json"></script>` 里的 JSON 串是 JS 相关的，应符合 JS 的命名规范，那么在 JS 里采用 Camel 命名，必要时可以选择 Pascal
