### ISSUE TITLE
【申请sandbox白名单】BMap，BMapLib

### ISSUE THREAD

**Issue by mrpeng** [mipengine/mip2#576]
**要解决什么问题**
使用百度地图功能

**描述一下你理想中的解决方案**
【申请sandbox白名单】BMap，BMapLib

**Comment by clark-t** [comment]
BMap 的添加可能会对 mip-map 组件造成影响，需要经过以下步骤进行上线：
1. mip-sandbox 增加 BMap、BMapLib 白名单；
2. mip-cli 更新 mip-sandbox，这样站长组件在编译的时候 BMap、BMapLib 将不受沙盒影响；
3. 修改 mip-map 并上线，解决问题；
4. mip.js 升级 mip-sandbox

**Comment by clark-t** [comment]
done
