### ISSUE TITLE
mip-iframe引用的地址不能滚动

### ISSUE THREAD

**Issue by chenruifu** [mipengine/mip2#580]
`<mip-iframe layout="fixed-height" width="100%" height="100vh" src="https://cs.tianxiang.com/liudaolunhui/?spread=yufangz"></mip-iframe>`

![image](https://user-images.githubusercontent.com/19771516/56334013-365e9600-61c9-11e9-91c7-973fcf103148.png)

**Comment by yenshih** [comment]
麻烦按照 issue 模板填写。
