### ISSUE TITLE
反馈:docs/contribute/getting-start/component-spec.md

### ISSUE THREAD

**Issue by jqqjj** [mipengine/mip2#581]
目录规范是不是未更新？

现在是：[MUST] components/mip-xxx 组件目录下，必须包含 ① example 示例，② vue 组件 mip-xxx.vue，③ 组件说明文件 README.md

用mip2 add 指令添加组件现在没有mip-xxx.vue这种类型的文件了，取页代之的是：mip-xxx.js这种文件和index.less这种文件

**Comment by clark-t** [comment]
收到反馈
