### ISSUE TITLE
在手机百度里面打开内置的图片浏览器

### ISSUE THREAD

**Issue by PengXing** [mipengine/mip2#582]
**要解决什么问题**

MIP 在手机百度里的体验没有达到 NA 2.0 的要求，目前为止唯一的问题是图片不支持手势放大缩小，为了最小化成本，前端不用实现手势放大的效果，而是直接改调用手机百度提供的图片阅读器

**描述一下你理想中的解决方案**

在手机百度里调用图片阅读器

**描述你的备选方案**

前端自己实现图片放大缩小

**Comment by zgycgc** [comment]
苹果电脑Qlab Mac版
