### ISSUE TITLE
仅允许使用类选择器编写样式

### ISSUE THREAD

**Issue by yenshih** [mipengine/mip2#586]
**要解决什么问题**
 - 复杂选择器问题多多，依赖 DOM 的嵌套结构，维护困难
 - 涉及 `<mip-fixed>` 的组件会破坏 DOM 结构，造成样式失效
 - 使得转小程序方案变得可行

**描述一下你理想中的解决方案**
```css
mip-foo {
  .title {
    // ...
  }
  .content {
    // ...
  }
}
.mip-foo-portal-element {
  // ...
}
```
```html
<style mip-custom>
  <!-- 同上 -->
</style>
```
**描述你的备选方案**
无

**补充信息**
无

**Comment by zoumiaojiang** [comment]
1、如果官方组件复杂的话，应该考虑使用 templates 方式去让开发者自己填充组件的内容，参考 mip-group-selection 组件
2、DOM 嵌套结构对组件的使用者来讲是最直观的样式，也比较好在外层直接添加类名或者 id 进行样式覆盖，官方组件的样式应该尽量设计的简单，层级明了，方便覆盖
3、为了兼容历史遗留问题，mip-fixed 现在统一需要添加 still 属性，可以保证 DOM 结构的破坏
