### ISSUE TITLE
npm白名单申请

### ISSUE THREAD

**Issue by huochezaodian** [mipengine/mip2#595]
**要申请的 npm 包名**
swiper

**描述一下添加该 npm 包的必要性**
需要控制轮播的方向，循环方式，间距以及左右部分显示，还有滑动的freemode，惯性滑动，以及兼容性问题

**补充信息**
mip-scrollbox 不带有回弹效果，只能引用外部的

**Comment by clark-t** [comment]
https://www.mipengine.org/v2/components/layout/mip-carousel.html 可以使用这个 mip-carousel 内部可以放 div

**Comment by huochezaodian** [comment]
> https://www.mipengine.org/v2/components/layout/mip-carousel.html 可以使用这个 mip-carousel 内部可以放 div

不行，一个它会不断循环这个div，没有不循环的选项

**Comment by clark-t** [comment]
done
