### ISSUE TITLE
您好，请问如何清除或替换 mip-vd-tabs tab 切换组件 的默认样式呢？

### ISSUE THREAD

**Issue by sz861128** [mipengine/mip2#596]
**BUG 描述**
由于项目要求，嵌入了 mip-vd-tabs tab 切换组件，但受组件默认样式，无法还原设计，请问如何替换或删除组件默认样式？

**尝试替换**
自己曾尝试自定义样式强制替换
mip-vd-tabs .mip-vd-tabs-nav {
  padding: 0 !important;
}
但代码并未成功，还望解答，谢谢！

**Comment by clark-t** [comment]
您好，可以通过自定义样式实现：
https://www.mipengine.org/v2/docs/mip-standard/mip-html-spec.html#4
