### ISSUE TITLE
希望增加user-scalable=no以及对scss预编译的支持

### ISSUE THREAD

**Issue by sz861128** [mipengine/mip2#599]
**要解决什么问题**
每次通过脚手架创建项目后，都需要在mate标签手动增加user-scalable=no属性，否则页面预览会导致页面操作放大。
目前支持less，但是相比scss，less的局限性太大，很多属性，比如retrue返回值等都无法使用。

**描述一下你理想中的解决方案**
创建项目后，mate增加user-scalable=no属性。
增加对scss的支持，支持后可以利用scss混淆快速对单位数值进行转换。

----------------------------------
望可以支持，万分感谢！

**Comment by clark-t** [comment]
1. 这个问题我们会尽快修复，感谢您的提醒；
2. 在 MIP 选型之初 sass 编译是依赖 ruby 环境的，我们并不打算把工具安装弄复杂，因此没有选择 sass。同时从项目维护的角度考虑，支持多种语法并不是一个明智的选择。因此 MIP 组件开发我们只打算支持 less

**Comment by clark-t** [comment]
已修复
