### ISSUE TITLE
on 事件执行 setData 时，如果数据表达式使用了括号，将无法执行

### ISSUE THREAD

**Issue by ccksfh** [mipengine/mip2#60]
**BUG 描述**
on 事件触发执行 MIP.setData 时，如果数据表达式使用了括号，将无法执行

**复现步骤**
```html
<mip-data>
  <script type="application/json">
  {
    "value": 1
  }
  </script>
</mip-data>
<h1 m-text="value" on="tap:MIP.setData({value:(m.value+1)})"></h1>
```
把表达式中的括号去掉就可以正常执行了，已验证过与 setData 方法无关

**期望结果**
点击触发 setData，h2内容随着点击自增

**环境及版本信息:**
没有特定环境

**Comment by PengXing** [comment]
提 ISSUE 的代码，也得符合代码标准[狗头]

**Comment by huanghuiquan** [comment]
参数是通过正则匹配的方式匹配的，具体正则[代码](https://github.com/mipengine/mip2/blob/master/packages/mip/src/util/event-action.js#L19) 
```js
const PARSE_REG = /^(\w+):([\w-]+)\.([\w-$]+)(?:\(([^)]+)\))?$/
```
正则无法匹配出参数 `{value:(m.value+1)}` 字符串

可修改正则为：
```js
const PARSE_REG = /^(\w+):([\w-]+)\.([\w-$]+)(?:\((.+)\))?$/
```

## 可能带来的问题

可通过 setData 执行任何代码，例如：
```js
<h1 m-text="value" on="tap:MIP.setData({x:alert('tedd')})"></h1>
```
上述代码点击后会弹窗，期待更好的解决方案
