### ISSUE TITLE
申请添加沙盒白名单 window.crypto

### ISSUE THREAD

**Issue by xin-** [mipengine/mip2#62]
**BUG 描述**
因项目需求，需要加密密码，使用到window.crypto，申请添加白名单

**Comment by PengXing** [comment]
crypto 的支持度不是很好，最终你可能还是得通过引入第三方的库来解决这个问题

![image](https://user-images.githubusercontent.com/527244/42921131-bf108304-8b4c-11e8-8b4d-94f0f840ca14.png)

**Comment by clark-t** [comment]
最新mip.js 核心以及 mip2@1.1.10 已实现
