### ISSUE TITLE
npm白名单 @baidu/m-antman

### ISSUE THREAD

**Issue by huochezaodian** [mipengine/mip2#623]
**要解决什么问题**
清晰准确的描述要解决什么问题
避免重复造轮子，基于mip集成的组件库

**描述一下你理想中的解决方案**
清晰准确的描述你想怎么解决

**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

**Comment by clark-t** [comment]
请给出相关组件库的链接

**Comment by clark-t** [comment]
done
