### ISSUE TITLE
需要一种机制可以允许站长加载第三方的公共的vue组件文件

### ISSUE THREAD

**Issue by VenyXiong** [mipengine/mip2#63]
极速服务接入的过程中，会设计到一些比较复杂的组件比如说filter组件和一些不同功能的picker组件，
这些组件中会包含大量的业务逻辑，这些不同的业务逻辑，我们很难将他们全都封装在一个mip组件中去完成。
所以执行上，我们更希望把这些复杂组件中涉及到的一些基础组件抽离出来，组织成一个个的带功能和样式的vue文件，
站长可以根据自己的业务需求，去组合这些vue组件，并定制自己的业务逻辑

比如说封装一个选择时间和日期的picker组件，可以组织的形式大概如下

![image](https://user-images.githubusercontent.com/3196280/42924274-05d459f0-8b5c-11e8-91ed-27469172b3bc.png)

这样我们会更关注更基础更细粒度的基础组件和UI样式，而不用去考虑站长自己的业务逻辑，
他们需要定制时，开发也相对比较简单。

**我们计划会提供这样一个vue的组件库**
**对于站长来的使用来说，这里需要一个机制去加载和管理这些公共的vue组件文件，而不是简单的文件拷贝。**

**Comment by chenqiushi** [comment]
我感觉这样的一个 vue 组件库不适合放在当前的 mip 组件仓库中来管理，毕竟 vue UI 组件和 mip 组件是两个不同的概念。

比较合适的方式是，把这个 vue UI 组件库以 npm 包的形式管理和发布，在 mip 组件中直接以 import 的方式来使用。前提是这些 vue 组件符合 mip 的开发规范，不会命中沙盒的限制等等。

如果后期支持了 npm package 的白名单，这种组件库应该是属于白名单的范畴之内的。

**Comment by VenyXiong** [comment]
继续补充一点

在对这些通用的业务逻辑无关的组件进行设计的时候，也考虑过采用mip组件的形式来提供，但是发现这种形式对开发者来说不是很友好。

主要体现在以下两点

第一个是mip组件的事件和vue组件的事件使用上有一些区别，虽然核心里做了一些适配，但是对于下面这个例子
![image](https://user-images.githubusercontent.com/3196280/42925979-94fbca18-8b62-11e8-9b9e-f5faea28e6fc.png)
如果mip-picker是一个mip组件的话，那么此时我在handleChange中拿到的数据就是一个Dom Event 对下，需要从e.detail 下面才能具体拿到传递出来的数据，这一点和传统的vue组件开发是有些不一致的，很容易给人造成困惑

第二点是，业务的复合组件的js资源依赖很不清晰，还是刚才上面那个例子，我的date-picker组件中使用了mip-picker组件，那么在使用时，我就需要在页面中同时引入mip-picker.js， 这样的关系会给后续组件和产品页面的更新带来较多的困难。
还是上面的case, 如果我需要在mip-user-picker中新增一个mip-switch的引用，那么我首先需要更新下我的页面上引用的js资源，然后再次上线组件文件。

这些都是我们在开发和迭代过程中都不希望看到的事情。

**Comment by PengXing** [comment]
如今天在 Hi 里的沟通

- MIP 后续会提供一套 MIP 的组件，而非提供 Vue 的组件，因为毕竟 MIP 是以 Web Components 为中心的。
- 关于引用 MIP 组件会导致依赖很多外链 JS，导致混乱的问题，后续会通过 Jet 自动合并依赖文件的方式，让开发者无需编写依赖的组件 JS
