### ISSUE TITLE
添加白名单 下拉刷新

### ISSUE THREAD

**Issue by zj8656** [mipengine/mip2#633]
要解决什么问题
项目中需要用到手动下拉刷新获取数据，使用第三方插件iscroll.js 第四版

描述一下你理想中的解决方案
希望能将该库加入白名单

描述你的备选方案
目前mip库里发现只有无限自动刷新加载数据，而非手动下拉，项目中需要手动下拉。如果有现有的组件请帮忙推荐下。

补充信息
具体功能可访问如下链接了解功能。
默认进入显示10条信息，手动下拉刷新加载10条，需要加载更多都是通过手动下拉触发实现
https://wap.ciweimao.com/book_list

**Comment by clark-t** [comment]
iscroll 已经在白名单里了
