### ISSUE TITLE
QQ 浏览器 fetch 调用失败

### ISSUE THREAD

**Issue by PengXing** [mipengine/mip2#638]
**BUG 描述**
QQ 浏览器 Android 下某个版本调用 fetch，因为 fetch polyfill 修改了`xhr.responseType = 'blob'`，导致请求发送失败

**期望结果**
QQ 浏览器下支持 fetch 的浏览器，不进行 fetch 复写处理

**环境及版本信息:**
 - OS: Android vivo x9 plus
 - Browser: QQ Browser
 - 浏览器 Version: 9.2.1

**Comment by clark-t** [comment]
我记得之前之所以对 QQ 浏览器强行做 polyfill 的原因是 QQ 浏览器的 polyfill 实现得有问题...所以如果要直接去掉的话不知道有没有问题：
https://github.com/github/fetch/issues/466
不过这也是 2 年前的 issue 了，有可能 QQ （微信）浏览器已经把这个问题修掉了也说不准
