### ISSUE TITLE
vuex

### ISSUE THREAD

**Issue by aaab456** [mipengine/mip2#647]
**要申请的 npm 包名**
vuex

**描述一下添加该 npm 包的必要性**
工程跨组件通信、状态管理

**补充信息**
ERROR 
以下 npm 包不在白名单范围内，请到项目 package.json 中移除相关 dependencies，并修改代码移除相关依赖。或者前往地址申请白名单：
https://github.com/mipengine/mip2/issues/new?template=npm_whiltelist_request.md

非白名单 npm 列表：
vuex

**Comment by clark-t** [comment]
当组件复杂到需要 vuex 管理状态的时候，就已经不是 MIP 组件了；
在开发站长组件前首先确认现有组件和机制是否能满足目前页面开发需求，如果不满足再考虑开发站长组件，并且站长组件请优先选择 custom element 的形式进行开发
