### ISSUE TITLE
MIP-IMG 组件下一张顺序错乱

### ISSUE THREAD

**Issue by wpj130** [mipengine/mip2#651]
**BUG 描述**
MIP-IMG 组件下一张顺序错乱，左滑下一张的时候和图片列表的数据不一致，而且有时候会出现两张一样相同的图片的问题，看起来像是 懒加载。。图片没有加载到还是啥？默认有懒加载吗？我看调试框信息 只有滑动到哪里图片才去请求

**复现步骤**
重新复现 Bug 的步骤
1.  左滑下一张
2. 图片列表错乱

**期望结果**
解决和回复

**截图**
无法截图。附上问题链接 http://m.heiguang.com/photography/syjc/20190704/80582.html

**环境及版本信息:**
未使用CLI 直接使用的JS文件，相应百度MIP加速

**其他信息**
暂无

**Comment by zoumiaojiang** [comment]
试了你的链接地址，没有复现你说的问题呢，是不是你在测试的时候网络环境不好的原因？或者麻烦描述清楚你测试的系统、机型、浏览器 等有助于定位问题的关键信息？

**Comment by wpj130** [comment]
你打开链接不要 进行滑动操作，直接点击一张图然后下一张翻动。。会发现的吧？你往下滑动 图片会加载完毕了不会出现这个问题

**Comment by wpj130** [comment]
> 试了你的链接地址，没有复现你说的问题呢，是不是你在测试的时候网络环境不好的原因？或者麻烦描述清楚你测试的系统、机型、浏览器 等有助于定位问题的关键信息？
你打开链接不要 进行滑动操作，直接点击一张图然后下一张翻动。。会发现的吧？你往下滑动 图片会加载完毕了不会出现这个问题

**Comment by wpj130** [comment]
> 你打开链接不要 进行滑动操作，直接点击一张图然后下一张翻动。。会发现的吧？你往下滑动 图片会加载完毕了不会出现这个问题

**Comment by wpj130** [comment]
> 试了你的链接地址，没有复现你说的问题呢，是不是你在测试的时候网络环境不好的原因？或者麻烦描述清楚你测试的系统、机型、浏览器 等有助于定位问题的关键信息？

你打开链接不要 进行滑动操作，直接点击一张图然后下一张翻动。。会发现的吧？你往下滑动 图片会加载完毕了不会出现这个问题

**Comment by PengXing** [comment]
Hi 确实是懒加载导致的，现状是可以接受的，不过我们还要继续看一下是否要改进这个问题。

**Comment by Brunoon** [comment]
问题已修复
