### ISSUE TITLE
增加对 less 打包前缀的支持

### ISSUE THREAD

**Issue by hitao123** [mipengine/mip2#653]
**要解决什么问题**
升级到 mip2，在写样式的时候，为了移动端一些兼容性，需要加样式前缀，这个原本是有 postcss 支持的, 官网冒事没有提到这个，估计还有一些人在写 css 在为添加前缀苦恼 

**描述一下你理想中的解决方案**
清晰准确的描述你想怎么解决

在 mip 组件外层 mip cli 初始化项目的时候，能初始化 postcss.config.js, 支持 autoprefixer

```
module.exports = {
    plugins: [
        require('autoprefixer')
    ]
};
```
**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

我看 mip2 源码 build webpack.base 是支持 postcss-loader的, 为啥这个文档上不加上

```
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: ('fonts/[name].[hash:7].[ext]')
        }
      }
```
@oott123

**Comment by clark-t** [comment]
请描述清楚具体的问题

**Comment by PengXing** [comment]
@hitao123 未补充其他信息前，我先关掉 ISSUE 了，后续根据情况你可以打开
