### ISSUE TITLE
【申请sandbox白名单】data-collection

### ISSUE THREAD

**Issue by Mrchensama** [mipengine/mip2#658]
**要解决什么问题**
新手第一次开发mip组件，一个留言面板组件，，开发完成后，使用mip2 validate验证通过后，mip2 build报错，提示该文件存在sandbox白名单之外 文件： mip2-extensions\conponents\mip-ananlytics\data-collection.js

**描述一下你理想中的解决方案**
清晰准确的描述你想怎么解决

**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
![image](https://user-images.githubusercontent.com/40376729/60958573-29b98c00-a339-11e9-93ee-bc62e377b916.png)

**Comment by Mrchensama** [comment]
因为是mip组件开发的新手，所以不敢确定是不是需要申请白名单，如果不需要申请白名单，请告知解决反感，百度查询没有相关帖子，谢谢。

**Comment by clark-t** [comment]
您好，我觉得您现在碰到的问题是，开发站长组件的时候选择的仓库不对，请 clone mip2-extensions-platform 进行提交

**Comment by clark-t** [comment]
https://www.mipengine.org/v2/contribute/getting-start/how-to-contribute.html#%E6%8F%90%E4%BA%A4%E7%AB%99%E9%95%BF%E7%BB%84%E4%BB%B6 
@Mrchensama 另外，在开发 MIP 站长组件之前请查看现有官方组件和官方文档看看 MIP 现有提供的组件和机制是否已经能很好地满足您的需求

**Comment by Mrchensama** [comment]
> 您好，我觉得您现在碰到的问题是，开发站长组件的时候选择的仓库不对，请 clone mip2-extensions-platform 进行提交

谢谢提醒，昨天已发现，未及时关闭issue。目前已在站长组件库提交pull-request等待审核。十分感谢

**Comment by Mrchensama** [comment]
> https://www.mipengine.org/v2/contribute/getting-start/how-to-contribute.html#%E6%8F%90%E4%BA%A4%E7%AB%99%E9%95%BF%E7%BB%84%E4%BB%B6
> @Mrchensama 另外，在开发 MIP 站长组件之前请查看现有官方组件和官方文档看看 MIP 现有提供的组件和机制是否已经能很好地满足您的需求

好的。非常感谢。这个issue我先关闭了哈。再次感谢
