### ISSUE TITLE
不同域名跳转外链后，通过shell 进行回到含有全局数据 的mip页，本地数据不能绑定

### ISSUE THREAD

**Issue by zhuguoxi** [mipengine/mip2#66]
**BUG 描述**
线上case
蓝犀牛在通过a链接 跳转支付宝进行支付时，并未跳出iframe下，通过shell 返回到首页，首页中含有全局数据
出现 全局数据可以进行m-bind到组件中，而本地数据无法进行绑定

**复现步骤**
提供测试url

**Comment by ccksfh** [comment]
因 sf 侧+mip 侧的 iframe 环境切换，mip-bind 未及时隔离第三方非 mip 页面导致报错，已修复。
