### ISSUE TITLE
申请添加vue-scratch-card0为白名单

### ISSUE THREAD

**Issue by eat-full** [mipengine/mip2#662]
**要申请的 npm 包名**
vue-scratch-card0

**描述一下添加该 npm 包的必要性**
营销落地页需要用到刮刮卡抽奖功能

**补充信息**
截图：
[https://raw.githubusercontent.com/ZENGzoe/imagesCollection/master/2018/scratchCard.gif](url)

包地址：
https://www.npmjs.com/package/vue-scratch-card0

**Comment by clark-t** [comment]
简易将该组件的代码直接复制到你们自己的项目里面去进行维护，这个包使用量较小而且不够规范，不建议申请白名单

**Comment by eat-full** [comment]
OK
