### ISSUE TITLE
在 PC 的百度快照里无法正常展现快照页

### ISSUE THREAD

**Issue by PengXing** [mipengine/mip2#667]
**BUG 描述**

PC 的百度快照里无法展现 MIP 的快照页面，原因是 mip.css 里设置了 `body:before` 遮住了页面，导致页面白屏。
![image](https://user-images.githubusercontent.com/527244/62339045-3d59ac00-b50d-11e9-8a2e-59f79e7b4b8d.png)

**复现步骤**

1. PC 上打开链接 [示例链接](http://cache.baiducontent.com/c?m=9f65cb4a8c8507ed19fa950d100b92235c438014638c92422381c814c4735b361a26b6a6787952468083267001d8131ab5ae22376a4376b8c493ca5ddccbc5747ad37b63&p=c0759a43819f12a05aaed4275a&newp=8b2a971986cc47e41afcdc654553d8224216ed673cd7c44324b9d71fd325001c1b69e7be24271301d4c7776402af4c5de0f43478341766dada9fca458ae7c474&user=baidu&fm=sc&query=mipengine&qid=b59c09f40077f327&p1=2)

**期望结果**
能够正常展现结果

**环境及版本信息:**
 - OS: 任意
 - Browser: PC Chrome

**其他信息**
无

**Comment by clark-t** [comment]
done
