### ISSUE TITLE
mipShellEvents 事件中能不能把 pageMeta 带过来

### ISSUE THREAD

**Issue by ShawnTu** [mipengine/mip2#68]
现在这个需求是，mip-shell扩展，页面切换时现在有
```
// togglePageMask 
// slide   // 页面上下滑动
// toggleTransition ----  toggle:false ( 页面开始切换 )
// toggleTransition ----  toggle:true（页面已切换）
// updateShell --- 开始更新shell  （目前含有pageMeta）
```
现在想要在 toggleTransition、toggleTransition 中事件数据中加入 current以及 next的  pageMeta

有这些数据中就可以 获取到目标页面数据，然后进行切换场景动画等

**Comment by easonyq** [comment]
我理解你们应该是需要切换页面时暴露出来一些钩子，然后你们可以进行相关操作。

现在切换页面和动画这块随着逻辑的逐渐复杂越来越难懂，我和宇琪打算明天把这个重构一下，届时可以提供钩子，就会清晰很多。

**Comment by easonyq** [comment]
见 #51 的评论说明。 
参数中的 `options.targetPageMeta` 和 `options.sourcePageMeta` 能满足你的需求。
