### ISSUE TITLE
a 标签 download 属性不起作用，不能下载资源

### ISSUE THREAD

**Issue by Brunoon** [mipengine/mip2#688]
**BUG 描述**

`<a href="https://boscdn.baidu.com/v1/assets/mipengine/logo.jpeg" download="build-test"> download </a>`

会直接跳转，无法下载图片

因为 MIP viewer 代理了所有 a 标签的点击事件并自定义了跳转行为，忽略了 download 属性和下载的情况

**复现步骤**
重新复现 Bug 的步骤

**期望结果**

能够点击下载图片

**截图**

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**

**Comment by clark-t** [comment]
download 属性在 iOS 下不生效
