### ISSUE TITLE
能把 css 里面的 img{width:100%;margin:0 auto} 去掉，或者换成 img{max-width:100%;margin:0 auto}

### ISSUE THREAD

**Issue by dxhuii** [mipengine/mip2#689]
**BUG 描述**
img{width:100%;margin:0 auto}
这个样式会导致页面上图片，没有加宽的情况下，就成100%宽，导致页面图片变形，特别是第三方广告，变形特别严重, 有的时候，图片也不一定要居中显示的，这样强制了图片样式，不太友好

> https://c.mipcdn.com/static/v2/mip.css  这个css

**期望结果**
img{width:100%;margin:0 auto} 删除 或者修改成 img{max-width:100%;margin:0 auto}

**Comment by clark-t** [comment]
请自行在自定义样式块里写 css 样式做覆盖，另外 `<mip-img>` 本身要指定 width height layout 属性才能够得到最佳的展示效果
