### ISSUE TITLE
前端预渲染方案

### ISSUE THREAD

**Issue by huanghuiquan** [mipengine/mip2#69]
# MIP 前端预渲染机制&方案

## 概述

MIP 预渲染即在结果页浏览期间，对部分 MIP 页面在后台提前创建 iframe 并进行文档预取和预解析渲染，在点击的同时将 iframe 进行展示并完成后续渲染加载。

## 预渲染触发机制

1. 结果页 JS 模块判断页面中有需要预加载的页面
2. 在触发 load 事件后尝试进行预渲染
3. 在用户点击预渲染好的结果时直接带着预渲染好的 iframe 页面滑入，动画完成后，继续渲染组件内容

## 预渲染机制

- 落地页预渲染环境获取：
在结果页创建 iframe 时传入 hash `#prerender=1`， 通过 hash 通知 mip 页面处于预渲染环境

- 组件生命周期 block：
MIP 核心初始化时获取`#prerender=1`, 初始化`MIP.env.prerender=true`，并监听`hashchange`事件，mip 页面内部组件通过判断运行时环境`MIP.env.prerender=true`选择阻塞 build 生命周期执行，并等待`MIP.env.prerender=false` 时才继续执行

- 激活 mip 组件生命周期
结果页在 iframe 动画结束后通过删除  hash `#prerender=1` 通知mip页面进入激活状态，触发 `MIP.env.prerender=false`，并继续执行 build 生命周期

> 注意：1. 在 connectedCallback 阻塞 build 回调； 2. attributeChangedCallback 也需要阻塞和激活；

- 显示声明不阻塞组件生命周期
开发者可以通过组件标签属性控制组件是否需要在预渲染期间阻塞 build 生命周期的执行，例如 mip-img 不需要阻塞图片加载，可以这么显示声明：

```
<mip-img src="xxx" prerender></mip-img>
```

### 预渲染时机选择

由于页面预渲染需要较重的运算、网络等资源，可能会导致结果页面造成短暂卡顿

### 预渲染内容

- 资源加载： 主文档 HTML、JS 资源、CSS 资源
- 渲染内容：
	- HTML 解析，内置标签 DOM 完全渲染
	- JS 加载和执行
	- CSS 样式应用
- 不会渲染的内容：
	- 不会执行组件 build 周期内的内容，包括生成组件内部结构
	- 由于 Vue 实例在build 周期内创建，所以预渲染也不会创建 Vue 实例

### mipSerivce

预渲染事实上提前创建了整个 view 与 scope，并执行了部分 iframe-shell 逻辑，使得其在固有的 DOM 上创建了对应节点以保证 iframe 不会被移动。

在部分 iOS 手百上，隐藏的 iframe 渲染可能在某些极端情况下导致手百卡死（似乎要求嵌套 iframe 内部调用了端能力，具体需要再测试），此处可能需要做出策略避让。

### mip 核心代码

mip 核心通过 hash 标记执行环境，通过注册 hashchange 事件回调阻止生命周期执行，并通过结果页激活iframe，并修改 hash 触发i frame 内 mip 标记环境变更为正常渲染模式，激活事件，继续执行 build 生命周期。

改造点：
1. mip 核心代码
2. 检查和确认内置组件影响渲染的代码再build周期之内
3. 规范业务组件的生命周期使用，确保预渲染下不执行的逻辑在 build 回调周期内，比如 ajax 请求

## 预渲染效果预期

1. 对站点而言，由于页面、脚本、样式本身都由 mip cache 提供，原理上对站长没有任何感知。
2. 只对文档 HTML 上直接使用的标签有效，对于组件内结构包含的 mip 组件标签无效（因为内部结构还没有被创建）
3. 预估MIP组件内部结构渲染的速度在 50ms 以内,下图是 build 开始到结束的打点时间（不包含图片和ajax之类的异步请求时间）
![图片](http://agroup-bos.su.bcebos.com/27a38eb3d639ef5f1d67c96afe47a6a2b096be12)

### 统计打点

1. mip 性能统计增加 buildStart 打点 和 buildEnd 打点
2. 若预渲染策略命中，前端性能指标统一记为 1ms 上报；若预渲染失败则忽略维持正常统计

> 如何确认 mip 页面首屏渲染完成？

## 其它问题

1. 预渲染需要网络加载大量资源，并且需要执行JS代码，需要考虑预渲染对结果页的影响，是否会导致结果页卡顿

**Comment by tayqassqan** [comment]
部分低端机是不适合预渲染，同时高端性能手机网络条件差时也不适合大量预渲染，这一块降级机制需要考虑

**Comment by huanghuiquan** [comment]
@tayqassqan mip核心预留预渲染的接口，具体预渲染的策略我觉得应该留给接入的结果页控制。

**Comment by huanghuiquan** [comment]
**使用说明**

- 设置预渲染环境：
  通过在 url 落地页添加 hash 值 `#prerender=1` 标识

  如落地页地址为 `http://localhost:8080/examples/builtin-components/mip-img.html`, 可通过示例代码的方式创建预渲染的环境：

  ```js
    function createPage(url) {
      iframe = document.createElement('iframe')
      iframe.scrolling = 'no'
      iframe.referrerpolicy = 'always'
      iframe.sandbox = 'allow-top-navigation allow-popups allow-scripts allow-forms allow-pointer-lock allow-popups-to-escape-sandbox allow-same-origin allow-modals'
      iframe.frameBorder = 0
      iframe.src = url + '#prerender=1'
      return iframe
    }

    createPage('http://localhost:8080/examples/builtin-components/mip-img.html')
  ```

- 显示声明不阻塞组件生命周期
  开发者可以通过组件标签属性控制组件是否需要在预渲染期间阻塞 build 生命周期的执行，例如 mip-img 不需要阻塞图片加载，可以这么显示声明：

  ```
   <mip-img src="xxx" prerender></mip-img>
   ```

**Comment by tayqassqan** [comment]
> 结果页在 iframe 动画结束后通过删除 hash #prerender=1 通知mip页面进入激活状态，触发 MIP.env.prerender=false，并继续执行 build 生命周期
这里需要具体明确是外部容器执行去除hash操作还是传递消息内部去除。此外，如果是内部去除，建议提供统一api，例如：`trigger("pageActive")`

**Comment by huanghuiquan** [comment]
@tayqassqan 这个通过 postMessage 来传递消息给内部吧

```js
iframe.contentWindow.postMessage('pageActive', window.location.origin)
```

**Comment by PengXing** [comment]
消息统一一种命名方式会不会好一些，比如都常量，`PAGE_ACTIVE`

**Comment by huanghuiquan** [comment]
> 消息统一一种命名方式会不会好一些，比如都常量，PAGE_ACTIVE

OK, @tayqassqan 确认下，没问题我就提交下代码

**Comment by tayqassqan** [comment]
没问题，但我们可以建立一个issue或doc，把消息命名维护起来

**Comment by easonyq** [comment]
我有个小问题：

> MIP 预渲染即在结果页浏览期间，对 __部分__ MIP 页面在后台提前创建 iframe 并进行文档预取和预解析渲染，在点击的同时将 iframe 进行展示并完成后续渲染加载。

这个 “__部分__ MIP 页面“ 是如何判断的？会不会存在一个搜索结果页内缓存了多个 MIP 页面，也就是背后隐藏了多个 iframe 的情况？

另外根据 MIP Shell 的开发过程中的经验来看，一边加载 iframe 一边执行其他 JS （或者其他交互操作，例如滚动）的确会非常卡顿，即便这个 iframe 是 display:none 的。这个体验在结果页上能够接受么？

**Comment by huanghuiquan** [comment]
@easonyq Good questions!

> 这个 “部分 MIP 页面“ 是如何判断的？会不会存在一个搜索结果页内缓存了多个 MIP 页面，也就是背后隐藏了多个 iframe 的情况？

是的，预渲染了多少 mip 页面就会有多少个隐藏 iframe， 这个 “部分 MIP 页面”是由结果页的策略来决定，比如结果页可以根据用户浏览习惯，点击位置频率，设备情况，网络情况等来决定预渲染多少个 mip 页面，以及渲染结果中的第几个等等

> 另外根据 MIP Shell 的开发过程中的经验来看，一边加载 iframe 一边执行其他 JS （或者其他交互操作，例如滚动）的确会非常卡顿，即便这个 iframe 是 display:none 的。这个体验在结果页上能够接受么？

这个是要等结果页面加载好了，也就是js执行完了，再执行预渲染 。如果用户刚好在交互，确实会导致卡顿，但是这个好像也没什么好办法可以避免

如果有更好的想法也可以提~

**Comment by easonyq** [comment]
第一个问题，看起来就和我们无关了，我们只负责提供支持，由结果页的策略去决定，当然成功率（【我们准备了】并且【用户点击了】）和失败率（【我们准备了】但是【用户没点击】）都由他们自己统计，控制和调节。

第二个问题，MIP Shell 的解决方法就是 iframe 加载的过程中啥都别干，消极避战……我不知道结果页的 JS 执行要多久，但我自己浏览百度的习惯，看到前几个结果渲染出来了就会去点，不知道那时候预渲染完成没有，如果没有那效果可能就比较差了，不过这也不是我们考虑的问题了。

**Comment by huanghuiquan** [comment]
update: 根据 https://github.com/mipengine/mip2/issues/215 MIP 核心和 SF 通讯消息整理，统一事件名命名规范
