### ISSUE TITLE
mip-script组件如何调用内置组件的方法

### ISSUE THREAD

**Issue by ivanfjz** [mipengine/mip2#717]
比如我通过自己的逻辑，需要特定情况下关闭或者显示mip-fixed组件。在mip-script组件里如何获取组件对象并使用组件的方法呢？

**Comment by clark-t** [comment]
mip-script 目前的定位是扩展 MIP 数据驱动的能力，因此在 mip-script 中只允许做数据监听、数据计算、数据修改，以及获取远程数据的能力：https://www.mipengine.org/v2/components/dynamic-content/mip-script.html，目前不支持获取组件对象并使用组件方法。
如果你想要关闭或显示 mip-fixed 组件的话，可以在该组件上绑定一个隐藏或显示的样式即可：https://www.mipengine.org/v2/docs/interactive-mip/data-driven.html#mbindclass-%E7%BB%91%E5%AE%9A-class
