### ISSUE TITLE
反馈:docs/components/layout/mip-fixed.md

### ISSUE THREAD

**Issue by ivanfjz** [mipengine/mip2#718]
data-slide 这个属性在IOS UC浏览器下效果感人啊......要么没效果，要么就是效果严重延迟

**Comment by ivanfjz** [comment]
仔细观察了下不是没有效果，只是效果有延迟，只有当滚动结束的时候才会触发效果。

我的手机是iphone 8，系统版本是13.1.2。目前尝试了safari,chrome,qq浏览器,百度APP都可以正常展示效果，只有uc浏览器会有效果延迟的问题

**Comment by clark-t** [comment]
最新版的 iOS 推出不久，我们尚未安排进行相关适配。不过既然您提到只有 uc 浏览器有这个问题，我们倾向于认为这属于浏览器自身问题，或许会在新版本 uc 浏览器当中得到修复。
