### ISSUE TITLE
mip-shell 增加对head中jsonld的获取

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip2#72]
**要解决什么问题**
在翻页后，this.currentPageMeta会更新为当前页面（iframe）内容，但获取不到document.head中json-ld配置。shell是否会考虑支持？

具体场景：小说shell主要用于目录和设置，一千章的小说配置会超级长。之前shell配置直接写在页面里，包含【上一页】【下一页】链接，但几千行的shell配置只有这两个是变量，可以提到头部json-ld中声明，保证shell配置每个页面相同，翻页时不需要再次异步发送shell目录配置请求。
![image](https://user-images.githubusercontent.com/8498677/43055654-665460ca-8e6a-11e8-8d33-d8c068b967b2.png)

**描述一下你理想中的解决方案**
增加this.currentHeadJsonld字段, 获取head中配置
![image](https://user-images.githubusercontent.com/8498677/43055817-5929006c-8e6b-11e8-8705-833b77d32a67.png)

**描述你的备选方案**
目前在bindAllEvents里面通过emitCustomEvent + data传递绕过问题

**Comment by PengXing** [comment]
这个问题，我更倾向于 shell 组件自己去获取，而不是提供统一的方法，我看小说组件也是这么做的

我把这个 ISSUE 关掉了，如果后面还需要在讨论，把这个 ISSUE 再打开就行
