### ISSUE TITLE
iframe里的页面mip-fixed组件不再有固定效果（IOS环境）

### ISSUE THREAD

**Issue by ivanfjz** [mipengine/mip2#722]
**BUG 描述**
IOS 浏览器环境下，iframe中的mip-fixed组件失效

**复现步骤**
IOS下任何浏览器，a页面通过mip-link链接打开B页面(B页面打开后在iframe下)，结果B页面中的mip-fixed组件不再有固定位置的效果

**期望结果**
虽然IOS系统下，我可以判断强制不使用mip-link跳转，但是如果页面来自百度搜索结果点击跳转，那么由于MIP缓存页面的原理，百度页面应该还是会把我的页面嵌入到iframe里（这种情况是我猜测的，我项目还没上线），页面的mip-fixed效果还是会有问题。

真心希望能指导下兼容的方式，非常感谢！

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - OS: IOS 13.1.3
 - Browser safari、百度APP
 - 浏览器 应该是最新版本
 - mip-cli 无

**其他信息**
无

**Comment by Brunoon** [comment]
mip-fixed 是可以在 iframe 中使用的，能否提供一下代码或者链接？也可以加 QQ 群交流：580967494
