### ISSUE TITLE
独立域名的mip站点到底如何正确退出，恢复成H5移动站

### ISSUE THREAD

**Issue by leoxiaoping** [mipengine/mip2#739]
由于自身原因，以前做的独立域名的mip站点需要恢复成H5移动站

官方一致没有给一个统一的正确方法

清除mip缓存似乎不行
使用了301跳转不行
关闭域名解析也不行，直接打不开了

**Comment by clark-t** [comment]
您好，您可以尝试在 robots.txt 里面屏蔽 MIP 的 UA 抓取，MIP 页面会在一段时间后自然清退掉
