### ISSUE TITLE
希望添加fastclick组件

### ISSUE THREAD

**Issue by xin-** [mipengine/mip2#76]
**要解决什么问题**
移动端浏览器click事件300ms延迟

**描述一下你理想中的解决方案**
mip官方提供fastclick插件，以去除延迟

**描述你的备选方案**
我们自己在组件内import fastclick 或者添加白名单

**补充信息**
开发环境 在手百中扫码打开的webview中有300ms延迟的问题

**Comment by huanghuiquan** [comment]
提一个 pr 到 mip-extensions 吧
组件名就叫 mip-fastclick 

```vue
<script>
  import FastClick from "fastclick";
  export default {
    mounted() {
      FastClick.attach(document.body)
    }
  }
</script>
```
