### ISSUE TITLE
mip-carousel支持传入索引参数

### ISSUE THREAD

**Issue by tayqassqan** [mipengine/mip2#77]
**要解决什么问题**
在类似图片切换的场景，希望能通过向mip-carousel传入跳转到的图片索引，实现定位到对应要预览的图片。

**描述一下你理想中的解决方案**
新增index参数

**Comment by tayqassqan** [comment]
此外，需新增switchTo API，配合外部调用切换

**Comment by PengXing** [comment]
https://github.com/mipengine/mip2/pull/93
