### ISSUE TITLE
页面切换支持 左至右方向

### ISSUE THREAD

**Issue by zhuguoxi** [mipengine/mip2#78]
**要解决什么问题**
目前MIP.viewer.open，只支持 从右到左进行打开页面，有些场景需要 从左至右的情况

**描述一下你理想中的解决方案**
MIP.viewer.open(xxx, {direct})

**Comment by zhuguoxi** [comment]
比如 shell 中增加底部bar，点击当前上一个bar时应该是从左至右打开，点击下一个bar时应该是从右至左打开

**Comment by easonyq** [comment]
和 #68 类似，我会对shell进行重构，把切换页面的函数暴露给子类，由子类继承并修改来实现。

给 `viewer.open` 增加 `direction` 我觉得不太好，因为以后如果谁要从上到下，从下到上等方向进行加载，shell 的代码将太多太复杂，毕竟都是打包到 mip.js 里面去的。

**Comment by zhuguoxi** [comment]
现在有没有办法支持反向的加载页面

**Comment by easonyq** [comment]
@zhuguoxi shell 重构的代码已经合并完毕，添加了动画钩子函数，大致说明见 #51 。
具体到你这个需求，你可以通过控制 loading 和 iframe 样式中的 `slide-enter-to`, `slide-leave-active` 等6个样式类来实现反向。通过继承动画钩子函数，判断特定条件，并应用反向的样式类来实现。

**Comment by PengXing** [comment]
这个解决方案太麻烦了，不重写 shell，就无法实现这个需求
