### ISSUE TITLE
希望 解决mip-script 不能引用模块问题

### ISSUE THREAD

**Issue by motopia** [mipengine/mip2#83]
**解决mip-script 不能引用模块问题**
目前在vue 组件 可以自由import 通用模块，本着数据驱动组件原则，希望能在mip-sciprt 处理所有数据相关，这样会需要引用一些通用模块处理一些通用数据处理逻辑，以达到每个页面能复用一些数据逻辑，目前mip-script  局限性很大，会导致每个页面一大堆重复脚本，更难说通用

**描述一下你理想中的解决方案**
能够像vue 组件一样 通过import 导入通用模块

**描述你的备选方案**
备选方案 至少能通过外部链接 引入一些通用模块打包后的库文件

**补充信息**
举例   import { httpGet } from 'httpUtil';

**Comment by PengXing** [comment]
`import` 这种方式在 mip-script 是不可取的，异步加载的 JS 无法保证安全性

不过，有两种方式可以解决这个问题，

## 支持 CORS 的异步 JS

如下

```html
<mip-script src="https://xxx.com/a.js"></mip-script>
```

这种方式的局限性，是这个 `src` 的地址必须设置 CORS，因为需要通过 `fetch` 来获取内容，并且保证独立站点和 MIP Cache 都能生效，这样才能对 `https://xxx.com/a.js` 进行安全性校验

## Worker

同上面一样，通用逻辑可以在写在同一个 JS 里，但这种方案不要求符合 CORS，因为将 JS 放在 worker 中去运行，通过 postMessage 来和父页面进行交互，很安全，但能进行的操作非常受限制

**Comment by PengXing** [comment]
@ccksfh 关注这个问题

**Comment by ccksfh** [comment]
web worker 本身也不支持加载跨域 js，worker 文件同样也要部署在同源服务下（或设置反向代理），一系列操作下来，可行性不如 mip-script 通过 CORS 支持异步 JS。mip-script 通过 CORS 支持异步 JS 与 mip-data 支持异步数据类似，开发者也不需要过多额外的成本。另外，worker 的操作实在是非常有限，和 strict.sandbox 也不一致，开发者需要适应和了解两套限制，不是很现实。

所以，我认为还是支持 mip-script  的异步 JS 方案比较好。已经排期开发
