### ISSUE TITLE
 Watch 变量 过程中， 频繁setData 该变量 会导致watch 不能触发同样次数 造成页面失效

### ISSUE THREAD

**Issue by motopia** [mipengine/mip2#84]
**BUG 描述**
 Watch 变量 过程中， 频繁setData 该变量 会导致watch 不能触发同样次数 造成页面失效

**复现步骤**
1. Click A button setData{ a:1}
2. Click B button setData{ a:2}
3. Click C button setData{ a:3}
4. ...
5. watch a 变量 发现触发次数跟上面点击不一致
**期望结果**
 watch 触发次数跟上面点击一致

**Comment by ccksfh** [comment]
能提供更详细的复现步骤吗？依据你的复现步骤我没有复现

**Comment by motopia** [comment]
1：页面内设置mip-data  {a:1}
2：通过m-bind：给到一个自定义a 组件，同时给到自定义组件B
3：在 a 组件有切换按钮，切换后调用setData更新 a 的值
4：同时 b 组件做一个watch（a）的动作，有变动，触发异步请求刷新当前页面数据
5：然后就出现 在a 组件重复切换几次 就直接卡主不动了 ，页面无任何效果，底层检测结果显示没有触发watch 动作

**Comment by motopia** [comment]
目前测试下来，没有之前明显了，但是加快频率切换，大概以20-30毫秒的速度切换 ，还是会出现

**Comment by ccksfh** [comment]
@motopia 请问数据 a 以及“异步请求刷新当前页面数据” 中的数据都是仅为页面数据，非全局数据是吗？约21:02的时候我们上线修复了一个数据设置问题，麻烦你进一步验证一下目前的效果。

我按照你的1-4步骤搭建复现场景（除去异步请求刷新当前页面数据这个），并且在页面 setInterval(10ms) setData({a: Date.now()})，watch 一直持续执行回调。如果验证还有问题，我们再进一步看看异步请求刷新当前页面数据这里的问题

**Comment by ccksfh** [comment]
经过了解和验证，结论最终为：
开发者理解的 watch 的触发时机与实际触发时机不同。

比如这样写：
```javascript
MIP.setData({
  a: var,
  loading: true
})

MIP.watch('a', function () {
  loading: false
})
```

开发者理想的执行时机是：设置 a、loading = true，执行 watch 回调，设置 loading = false
目前实际的触发时机是：设置 a 数据时就会 触发 a 的 watch 回调，从而设置 loading = false，然后回到之前那次设置上，设置了 loading = true

如果先把 setData 指定的数据都设置完再触发所有相应的回调，假设要设置的数据为13k 左右，setData 的时间约0.8ms，其实也可以忽略不计。假如设置完数据之后要触发的 watcher 也很多呢？或者设置的是全局数据，还涉及到数据广播的时间，以及待执行 watcher 同步执行的时机和顺序问题
关键是什么样的触发时机才是合适的
我会先参考一下 Vue 的相关 nextTick 实现，结合 mip-bind 现有机制再来 update 解决方案。也欢迎大家讨论
