### ISSUE TITLE
MIP.sandbox 沙盒不支持 new Function 的问题

### ISSUE THREAD

**Issue by motopia** [mipengine/mip2#88]
**MIP.sandbox 沙盒不支持 new Function 的问题**
需要引用模板字符串本身，在需要时执行
// 写法一
var str = 'return ' + '`Hello ${name}!`';
var func = new Function('name', str);
func('Amy');    // "Hello Amy!"

// 写法二
var str = '(name) => `Hello ${name}!`';
var func = eval.call(null, str);
func('Amy');    // "Hello Amy!"

**能执行上面代码**
添加白名单支持，支持new Function 语法

**描述你的备选方案**
支持eval

**补充信息**
TypeError: Cannot read property 'call' of undefined
TypeError: MIP.sandbox.FUnction is not a constructor @clark-t

**Comment by zoumiaojiang** [comment]
new Function 不予以支持的，可能会导致 xss 等问题，这种模版字符串的需求不需要借助 new Function 或者 eval 也能实现的，比如正则匹配？
