### ISSUE TITLE
轮播组件里面使用mip-img组件不支持懒加载，图片一次性全加载了，望修复此bug

### ISSUE THREAD

**Issue by ClimbYU** [mipengine/mip2#89]
#在组件mip-carousel中使用mip-img标签时会一次性加载全部的图片，没有实现懒加载
如下图所示：一次性加载了全部图片

![default](https://user-images.githubusercontent.com/26087303/43255852-8c1c12fe-90fd-11e8-85f3-a4c23c5e4e9b.png)

**Comment by PengXing** [comment]
这个 ISSUE 依赖于 ISSUE https://github.com/mipengine/mip2/issues/77 的修复，先等等吧

**Comment by tayqassqan** [comment]
组件在vue的slot中动态创建时，懒加载依然失效，具体代码示例如下：
<mip-carousel> <block v-for="(item,index ) in this.imageitems" :key="index"> <mip-img style="height:5rem" :src="item.pic"></mip-img> </block> </mip-carousel>
