### ISSUE TITLE
全局共享组件方案

### ISSUE THREAD

**Issue by xiaoiver** [mipengine/mip2#9]
## 问题背景

目前在根页面中以 iframe 方式打开多个子页面，各个子页面渲染各自的自定义组件。
有一种需求是类似登录框这样的组件，并不需要每个页面都渲染一遍，而是应该由**根页面**统一负责渲染。

例如目前的 `<mip-shell>`，虽然每个页面都会写在各自的 HTML 中，但实际只会在根页面中运行。
更类似于一种全局性的配置文件。

而全局组件比 `<mip-shell>` 更加复杂，因为可能会与页面中其他组件交互。

## 大致思路

在子页面中，在自定义组件注册之前，一旦识别到全局组件（加上特殊的 attribute），向根页面通过 `postMessage` 发送组件 DOM 结构（字符串形式），然后从 DOM 中删除避免触发 `connectedCallback`。

根页面接收到事件，如果当前不存在这个全局唯一的组件，请求组件对应的 JS，插入 DOM 结构开始渲染。

可能存在的问题是和原子页面中其他组件的交互。不过如果统一使用全局的状态数据，似乎子页面其他组件也不用关心这个全局组件的具体渲染细节。

**Comment by easonyq** [comment]
按照目前的初始化顺序，`Vue.use(vueCustomElement)` 在前，而 `viewer.init()` 在后。`viewer.init()` 里面调用了 `page` 的构造函数和初始化。因此如果要实现思路中的“自定义注册之前向根页面 `postMessage`” 就需要调整这里的顺序，在构造 custom element 之前进行一些处理。

**Comment by PengXing** [comment]
经过分析，第一期的需求只有把 header 隐藏

因此，为了保证按时上线，在第一期只提供隐藏头部的功能，暂时不实现全局组件的方案

**Comment by windtalkers** [comment]
1. 个人觉得不要造一个全局组件的概念，理论上，组件就是组件，概念是很明确的。
2. 这里的全局概念，是需要全局运行组件的一个runtime机制，通过runtime机制，提供不同的API或者事件给组件开发者，在这个机制下面，运行的是哪个组件，可以有多种方式来控制或者限制，当然也可以不限制，但是不建议从组件维度来增加概念。
当然，实现上，思路上可能和上面是一致的，但是对于开发者来说，概念就没有那么多，而且抽象本身是从机制的角度提供组件runtime，这样开发者需求明确后，就从机制的角度，思考组件怎么去实现。
