### ISSUE TITLE
<mip-fixed> 改进方案

### ISSUE THREAD

**Issue by xiaoiver** [mipengine/mip2#90]
**要解决什么问题**

## 问题背景

在 iOS 的 `<iframe>` 中，如果页面中包含了使用 `display: fixed` 定位的元素，在页面发生滚动时，这些元素并不会遵循 `fixed` 的特性停留在页面的同一位置，而会发生明显的上下跳动，十分影响视觉效果。

为了解决这个问题，我们会创建一个 `<body>` 的兄弟节点，将原有页面中所有的 fixed 元素移动到这个节点中。此时原始的 HTML 结构会发生一个明显的改变：

```html
<html>
  <body><!-- 原始内容 --></body>
  <body id="mip-fixedlayer">
    <!-- 所有 mip-fixed 元素被移动到了这里 -->
    <mip-fixed></mip-fixed>
  </body>
</html>
```

但是由于发生了移动，会带来很多使用上的问题。
1. 动态创建的 `<mip-fixed>` 需要调用 `MIP.viewer.fixedElement.init()` 或者类似的刷新方法
2. 针对 `<mip-fixed>` 的选择器不能存在嵌套
3. 委托事件时不能选择 `document.body`

详见 [API 文档](https://github.com/mipengine/mip2/blob/master/docs/api/viewer.md#fixedelement)中的问题描述以及解决方法。

**描述一下你理想中的解决方案**

关于第一点我已经把 `<mip-fixed>` 改造成了真正的自定义元素，也就是说开发者在使用时已经不需要手动调用方法了（已经这么做的也可以不改）。
但是第二，第三点目前没想到更好的办法。其中个人认为第二点比较关键。

**Comment by jenkey2011** [comment]
既然是ios发生scroll时出现的问题，那么解决scroll问题，不久没有问题123了么……

**Comment by zoumiaojiang** [comment]
在 mip1 的存量站点中，如果都统一的将 mip-fixed 挪到 body 外在 mip-fixed 是动态插入或者有 dom 操作依赖的情况下会存在兼容性问题，现在的方案是在 mip1 的组件中全部新增 still 属性来规避对现有站点和组件的影响。
