### ISSUE TITLE
mip-lightbox 弹出层组件在打开与关闭时没有相应的事件处理，导致无法在弹层打开或关闭时做相应业务逻辑处理

### ISSUE THREAD

**Issue by ClimbYU** [mipengine/mip2#92]
mip-lightbox 弹出层组件在打开与关闭时没有相应的事件处理，导致无法在弹层打开或关闭时做相应业务逻辑处理

**Comment by PengXing** [comment]
mip2 中暂时还没有 mip-lightbox 组件，你得到 https://github.com/mipengine/mip-extensions/issues 这里去提这个 ISSUE
