### ISSUE TITLE
钱包-统一登录分散认证需要用到的全局属性-添加白名单

### ISSUE THREAD

**Issue by xin-** [mipengine/mip2#95]
**要申请的 npm 包名**
document.domain
window.qianbaoAuthoricationConfig

**描述一下添加该 npm 包的必要性**
钱包这边的登录需要分散认证，需要用到domain 以及全局定义的qianbaoAuthoricationConfig，需要添加白名单

**补充信息**

**Comment by PengXing** [comment]
能描述一下具体方案吗？比如说什么方案下要使用

**Comment by clark-t** [comment]
mip-sandbox@1.0.21 已新增 document.domain 豁免，qianbaoAuthoricationConfig 不具有通用型因此打回
